//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/oe/Cart.java
//
//  Created by decoteaud on 11/30/15.
//

#ifndef _CCPBVCart_H_
#define _CCPBVCart_H_

@class CCPBVOrder;
@class JavaUtilEventObject;
@class RAREActionLink;
@class RAREExpansionEvent;
@class RAREListBoxViewer;
@protocol JavaUtilList;
@protocol RAREiContainer;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/iFunctionCallback.h"
#include "com/appnativa/rare/ui/event/iExpansionListener.h"
#include "com/sparseware/bellavista/aEventHandler.h"
#include "java/lang/Runnable.h"

@interface CCPBVCart : CCPBVaEventHandler {
 @public
  id<RAREiContainer> actionbar_;
}

- (void)dataParsedWithRAREiWidget:(id<RAREiWidget>)widget
                 withJavaUtilList:(id<JavaUtilList>)rows
               withRAREActionLink:(RAREActionLink *)link;
- (void)onDisposeWithNSString:(NSString *)eventName
              withRAREiWidget:(id<RAREiWidget>)widget
      withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onConfigureWithNSString:(NSString *)eventName
                withRAREiWidget:(id<RAREiWidget>)widget
        withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onCartWillExpandWithNSString:(NSString *)eventName
                     withRAREiWidget:(id<RAREiWidget>)widget
             withJavaUtilEventObject:(JavaUtilEventObject *)event;
+ (id<JavaUtilList>)createCartList;
- (void)onEmptyCartWithNSString:(NSString *)eventName
                withRAREiWidget:(id<RAREiWidget>)widget
        withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onDeleteOrderWithNSString:(NSString *)eventName
                  withRAREiWidget:(id<RAREiWidget>)widget
          withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)checkForIncompleteOrdersWithRAREListBoxViewer:(RAREListBoxViewer *)lb;
- (void)onCartActionWithNSString:(NSString *)eventName
                 withRAREiWidget:(id<RAREiWidget>)widget
         withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onSubmitWithNSString:(NSString *)eventName
             withRAREiWidget:(id<RAREiWidget>)widget
     withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onSubmitOrderWithNSString:(NSString *)eventName
                  withRAREiWidget:(id<RAREiWidget>)widget
          withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onCloseWithNSString:(NSString *)eventName
            withRAREiWidget:(id<RAREiWidget>)widget
    withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)closePopupOrWindowWithRAREiWidget:(id<RAREiWidget>)widget;
- (id)init;
- (void)copyAllFieldsTo:(CCPBVCart *)other;
@end

J2OBJC_FIELD_SETTER(CCPBVCart, actionbar_, id<RAREiContainer>)

typedef CCPBVCart ComSparsewareBellavistaOeCart;

@interface CCPBVCart_$1 : NSObject < RAREiExpansionListener > {
 @public
  CCPBVCart *this$0_;
  RAREListBoxViewer *val$lb_;
}

- (void)itemWillExpandWithRAREExpansionEvent:(RAREExpansionEvent *)event;
- (void)itemWillCollapseWithRAREExpansionEvent:(RAREExpansionEvent *)event;
- (id)initWithCCPBVCart:(CCPBVCart *)outer$
  withRAREListBoxViewer:(RAREListBoxViewer *)capture$0;
@end

J2OBJC_FIELD_SETTER(CCPBVCart_$1, this$0_, CCPBVCart *)
J2OBJC_FIELD_SETTER(CCPBVCart_$1, val$lb_, RAREListBoxViewer *)

@interface CCPBVCart_$2 : NSObject < RAREiFunctionCallback > {
 @public
  CCPBVCart *this$0_;
  id<RAREiWidget> val$widget_;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (id)initWithCCPBVCart:(CCPBVCart *)outer$
        withRAREiWidget:(id<RAREiWidget>)capture$0;
@end

J2OBJC_FIELD_SETTER(CCPBVCart_$2, this$0_, CCPBVCart *)
J2OBJC_FIELD_SETTER(CCPBVCart_$2, val$widget_, id<RAREiWidget>)

@interface CCPBVCart_$3 : NSObject < RAREiFunctionCallback > {
 @public
  CCPBVCart *this$0_;
  CCPBVOrder *val$order_;
  RAREListBoxViewer *val$lb_;
  int val$row_;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (id)initWithCCPBVCart:(CCPBVCart *)outer$
         withCCPBVOrder:(CCPBVOrder *)capture$0
  withRAREListBoxViewer:(RAREListBoxViewer *)capture$1
                withInt:(int)capture$2;
@end

J2OBJC_FIELD_SETTER(CCPBVCart_$3, this$0_, CCPBVCart *)
J2OBJC_FIELD_SETTER(CCPBVCart_$3, val$order_, CCPBVOrder *)
J2OBJC_FIELD_SETTER(CCPBVCart_$3, val$lb_, RAREListBoxViewer *)

@interface CCPBVCart_$4 : NSObject < JavaLangRunnable > {
 @public
  CCPBVOrder *val$o_;
}

- (void)run;
- (id)initWithCCPBVOrder:(CCPBVOrder *)capture$0;
@end

J2OBJC_FIELD_SETTER(CCPBVCart_$4, val$o_, CCPBVOrder *)

@interface CCPBVCart_$5 : NSObject < RAREiFunctionCallback > {
 @public
  CCPBVCart *this$0_;
  RAREListBoxViewer *val$lb_;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (id)initWithCCPBVCart:(CCPBVCart *)outer$
  withRAREListBoxViewer:(RAREListBoxViewer *)capture$0;
@end

J2OBJC_FIELD_SETTER(CCPBVCart_$5, this$0_, CCPBVCart *)
J2OBJC_FIELD_SETTER(CCPBVCart_$5, val$lb_, RAREListBoxViewer *)

@interface CCPBVCart_$6 : NSObject < RAREiFunctionCallback > {
 @public
  CCPBVCart *this$0_;
  RAREListBoxViewer *val$lb_;
  int val$row_;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (id)initWithCCPBVCart:(CCPBVCart *)outer$
  withRAREListBoxViewer:(RAREListBoxViewer *)capture$0
                withInt:(int)capture$1;
@end

J2OBJC_FIELD_SETTER(CCPBVCart_$6, this$0_, CCPBVCart *)
J2OBJC_FIELD_SETTER(CCPBVCart_$6, val$lb_, RAREListBoxViewer *)

#endif // _CCPBVCart_H_
