//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/oe/FieldValue.java
//
//  Created by decoteaud on 11/18/15.
//

#ifndef _CCPBVFieldValue_H_
#define _CCPBVFieldValue_H_

@class RAREUTJSONObject;

#import "JreEmulation.h"

@interface CCPBVFieldValue : NSObject < NSCopying > {
 @public
  id value_;
  NSString *displayValue_;
  RAREUTJSONObject *field_;
  RAREUTJSONObject *groupField_;
}

- (id)initWithRAREUTJSONObject:(RAREUTJSONObject *)field;
- (id)initWithRAREUTJSONObject:(RAREUTJSONObject *)field
                        withId:(id)value;
- (id)initWithId:(id)value
    withNSString:(NSString *)displayValue;
- (void)clear;
- (void)reset;
- (id)clone;
- (NSString *)valueToString;
- (NSString *)description;
- (CCPBVFieldValue *)copy__ OBJC_METHOD_FAMILY_NONE;
- (id)copyWithZone:(NSZone *)zone;
- (void)copyAllFieldsTo:(CCPBVFieldValue *)other;
@end

J2OBJC_FIELD_SETTER(CCPBVFieldValue, value_, id)
J2OBJC_FIELD_SETTER(CCPBVFieldValue, displayValue_, NSString *)
J2OBJC_FIELD_SETTER(CCPBVFieldValue, field_, RAREUTJSONObject *)
J2OBJC_FIELD_SETTER(CCPBVFieldValue, groupField_, RAREUTJSONObject *)

typedef CCPBVFieldValue ComSparsewareBellavistaOeFieldValue;

#endif // _CCPBVFieldValue_H_
