//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/service/iHttpConnection.java
//
//  Created by decoteaud on 3/14/16.
//

#ifndef _CCPBViHttpConnection_H_
#define _CCPBViHttpConnection_H_

@class CCPBVContentWriter;
@class JavaNetHttpURLConnection;
@class JavaNetURL;

#import "JreEmulation.h"

@protocol CCPBViHttpConnection < NSObject, JavaObject >
- (NSString *)getResquestHeaderWithNSString:(NSString *)name;
- (NSString *)getRequestMethod;
- (JavaNetURL *)getURL;
- (CCPBVContentWriter *)getContentWriter;
- (void)setConnectionPipeWithJavaNetHttpURLConnection:(JavaNetHttpURLConnection *)connection;
@end

#define ComSparsewareBellavistaServiceIHttpConnection CCPBViHttpConnection

#endif // _CCPBViHttpConnection_H_
