//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/ActionPath.java
//
//  Created by decoteaud on 3/12/15.
//

#ifndef _ComSparsewareBellavistaActionPath_H_
#define _ComSparsewareBellavistaActionPath_H_

@class IOSObjectArray;
@protocol JavaUtilList;

#import "JreEmulation.h"
#include "java/util/ArrayList.h"

@interface ComSparsewareBellavistaActionPath : JavaUtilArrayList {
 @public
  id linkedData_;
}

- (id)init;
- (id)initWithInt:(int)pathCount;
- (id)initWithJavaUtilList:(id<JavaUtilList>)path;
- (id)initWithNSStringArray:(IOSObjectArray *)path;
- (void)addPathWithNSStringArray:(IOSObjectArray *)path;
- (ComSparsewareBellavistaActionPath *)copy__ OBJC_METHOD_FAMILY_NONE;
- (NSString *)peek;
- (NSString *)shiftPeek;
- (NSString *)pop;
- (void)pushWithNSString:(NSString *)path;
- (NSString *)see;
- (NSString *)shift;
- (NSString *)description;
- (void)unshiftWithNSString:(NSString *)path;
- (id)getLinkedData;
- (void)setLinkedDataWithId:(id)linkedData;
+ (ComSparsewareBellavistaActionPath *)fromStringWithNSString:(NSString *)path;
- (void)copyAllFieldsTo:(ComSparsewareBellavistaActionPath *)other;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaActionPath, linkedData_, id)

@protocol ComSparsewareBellavistaActionPath_iActionPathSupporter < NSObject, JavaObject >
- (ComSparsewareBellavistaActionPath *)getDisplayedActionPath;
- (void)handleActionPathWithComSparsewareBellavistaActionPath:(ComSparsewareBellavistaActionPath *)path;
@end

#endif // _ComSparsewareBellavistaActionPath_H_
