//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/aRemoteMonitor.java
//
//  Created by decoteaud on 1/15/15.
//

#ifndef _ComSparsewareBellavistaaRemoteMonitor_H_
#define _ComSparsewareBellavistaaRemoteMonitor_H_

#import "JreEmulation.h"

@interface ComSparsewareBellavistaaRemoteMonitor : NSObject {
}

- (id)init;
@end

#endif // _ComSparsewareBellavistaaRemoteMonitor_H_
