//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/aResultsManager.java
//
//  Created by decoteaud on 3/12/15.
//

#ifndef _ComSparsewareBellavistaaResultsManager_H_
#define _ComSparsewareBellavistaaResultsManager_H_

@class ComSparsewareBellavistaActionPath;
@class ComSparsewareBellavistaResultsViewEnum;
@class ComSparsewareBellavistaaChartHandler;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaUtilEventObject;
@class JavaUtilHashMap;
@class JavaUtilLinkedHashMap;
@class JavaUtilLinkedHashSet;
@class RARERenderableDataItem;
@class RAREStackPaneViewer;
@class RARETableViewer;
@class RAREWindowViewer;
@protocol JavaUtilList;
@protocol RAREiContainer;
@protocol RAREiTransitionAnimator;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/aWorkerTask.h"
#include "com/sparseware/bellavista/ActionPath.h"
#include "com/sparseware/bellavista/aEventHandler.h"
#include "java/lang/Runnable.h"

@interface ComSparsewareBellavistaaResultsManager : ComSparsewareBellavistaaEventHandler < ComSparsewareBellavistaActionPath_iActionPathSupporter > {
 @public
  ComSparsewareBellavistaResultsViewEnum *currentView_;
  RARETableViewer *dataTable_;
  RARETableViewer *spreadsheetTable_;
  BOOL hasNoData_;
  BOOL dataLoaded_;
  int spreadsheetPosition_;
  int spreadSheetPageSize_;
  int dataPageSize_;
  NSString *namePrefix_;
  ComSparsewareBellavistaaChartHandler *chartHandler_;
  id<RAREiTransitionAnimator> transitionAnimation_;
  id<JavaUtilList> originalRows_;
  JavaUtilLinkedHashMap *itemCounts_;
  IOSObjectArray *itemDates_;
  JavaUtilLinkedHashSet *itemDatesSet_;
  BOOL chartsLoaded_;
  ComSparsewareBellavistaActionPath *keyPath_;
  id dateContext_;
  NSString *scriptClassName_;
  BOOL selectionChecked_;
  BOOL multiChartMode_;
  JavaUtilHashMap *chartableItems_;
}

+ (int)DATE_POSITION;
+ (int *)DATE_POSITIONRef;
+ (int)NAME_POSITION;
+ (int *)NAME_POSITIONRef;
+ (int)VALUE_POSITION;
+ (int *)VALUE_POSITIONRef;
+ (int)RANGE_POSITION;
+ (int *)RANGE_POSITIONRef;
+ (int)MIN_ANGLED_LABEL_HEIGHT;
+ (int *)MIN_ANGLED_LABEL_HEIGHTRef;
+ (int)MIN_POINTSLABEL_HEIGHT;
+ (int *)MIN_POINTSLABEL_HEIGHTRef;
- (id)initWithNSString:(NSString *)namePrefix
          withNSString:(NSString *)scriptClassName;
- (void)chooseStartingDateWithNSString:(NSString *)eventName
                       withRAREiWidget:(id<RAREiWidget>)widget
               withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onChartFlingWithNSString:(NSString *)eventName
                 withRAREiWidget:(id<RAREiWidget>)widget
         withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (ComSparsewareBellavistaActionPath *)getDisplayedActionPath;
- (void)handleActionPathWithComSparsewareBellavistaActionPath:(ComSparsewareBellavistaActionPath *)path;
- (void)handleActionPathExWithComSparsewareBellavistaActionPath:(ComSparsewareBellavistaActionPath *)path;
- (void)addCurrentPathIDWithComSparsewareBellavistaActionPath:(ComSparsewareBellavistaActionPath *)path;
- (void)onChartScaleWithNSString:(NSString *)eventName
                 withRAREiWidget:(id<RAREiWidget>)widget
         withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onChartResizeWithNSString:(NSString *)eventName
                  withRAREiWidget:(id<RAREiWidget>)widget
          withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)spreadsheetRowCreatedWithRARETableViewer:(RARETableViewer *)table
                      withRARERenderableDataItem:(RARERenderableDataItem *)spreadsheetRow
                      withRARERenderableDataItem:(RARERenderableDataItem *)sourceRow;
- (void)clearSelection;
- (void)updateSpreadsheetRowsWithRARETableViewer:(RARETableViewer *)table;
- (void)showChartForSelectedItemWithRARETableViewer:(RARETableViewer *)table;
- (void)clearChartsWithRARETableViewer:(RARETableViewer *)table;
- (void)showMostRecentWithNSString:(NSString *)eventName
                   withRAREiWidget:(id<RAREiWidget>)widget
           withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)showNextResultSetWithNSString:(NSString *)eventName
                      withRAREiWidget:(id<RAREiWidget>)widget
              withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)changeViewWithNSString:(NSString *)eventName
               withRAREiWidget:(id<RAREiWidget>)widget
       withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)changeViewWithNSString:(NSString *)name
               withRAREiWidget:(id<RAREiWidget>)widget;
- (void)changeViewExWithComSparsewareBellavistaResultsViewEnum:(ComSparsewareBellavistaResultsViewEnum *)view;
- (void)showPreviousResultSetWithNSString:(NSString *)eventName
                          withRAREiWidget:(id<RAREiWidget>)widget
                  withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)showChartForSelectedItemExWithRARETableViewer:(RARETableViewer *)table
                              withRAREStackPaneViewer:(RAREStackPaneViewer *)sp
                                  withJavaLangBoolean:(JavaLangBoolean *)forward
                                          withBoolean:(BOOL)horizontal;
- (BOOL)hasCategories;
- (NSString *)getCategoryWithRARERenderableDataItem:(RARERenderableDataItem *)row;
- (void)selectTableIndexWithRARETableViewer:(RARETableViewer *)table
                                    withInt:(int)index;
- (void)updateSpreadsheetColumnsWithRARETableViewer:(RARETableViewer *)table;
- (void)changePageWithRAREiWidget:(id<RAREiWidget>)widget
                      withBoolean:(BOOL)forward
                      withBoolean:(BOOL)jump;
- (void)showSpreesheetWithRAREiContainer:(id<RAREiContainer>)fv;
- (void)showRegularTableWithRAREiContainer:(id<RAREiContainer>)fv
                               withBoolean:(BOOL)trends;
- (NSString *)getSpeeedSheetColumnTitle;
- (void)setNavigationButtonsVisibleWithRAREiContainer:(id<RAREiContainer>)fv
                                          withBoolean:(BOOL)visible;
- (void)updateNavigationButtonsWithRAREiContainer:(id<RAREiContainer>)fv;
- (void)onChartsPanelLoadedWithNSString:(NSString *)eventName
                        withRAREiWidget:(id<RAREiWidget>)widget
                withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (NSString *)getFirstChartableKey;
- (NSString *)getSelectedChartableKey;
- (int)getFirstChartableItemWithRARETableViewer:(RARETableViewer *)table;
- (void)selectFirstChartableItemWithRARETableViewer:(RARETableViewer *)table
                                        withBoolean:(BOOL)fireAction;
- (BOOL)isOnNonChartingView;
- (void)onDisposeWithNSString:(NSString *)eventName
              withRAREiWidget:(id<RAREiWidget>)widget
      withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onFirstPageWithNSString:(NSString *)eventName
                withRAREiWidget:(id<RAREiWidget>)widget
        withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onLastPageWithNSString:(NSString *)eventName
               withRAREiWidget:(id<RAREiWidget>)widget
       withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onNextPageWithNSString:(NSString *)eventName
               withRAREiWidget:(id<RAREiWidget>)widget
       withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onPreviousPageWithNSString:(NSString *)eventName
                   withRAREiWidget:(id<RAREiWidget>)widget
           withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onZoomInActionWithNSString:(NSString *)eventName
                   withRAREiWidget:(id<RAREiWidget>)widget
           withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onZoomOutActionWithNSString:(NSString *)eventName
                    withRAREiWidget:(id<RAREiWidget>)widget
            withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onTableActionWithNSString:(NSString *)eventName
                  withRAREiWidget:(id<RAREiWidget>)widget
          withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onTableCreatedWithNSString:(NSString *)eventName
                   withRAREiWidget:(id<RAREiWidget>)widget
           withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)reselectDefaultViewWithNSString:(NSString *)eventName
                        withRAREiWidget:(id<RAREiWidget>)widget
                withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onTimeframePopupActionWithNSString:(NSString *)eventName
                           withRAREiWidget:(id<RAREiWidget>)widget
                   withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)slideToChartableItemWithBoolean:(BOOL)next
                            withBoolean:(BOOL)horizontal;
- (BOOL)isChartableWithRARERenderableDataItem:(RARERenderableDataItem *)row;
- (void)handlePathKeyWithRARETableViewer:(RARETableViewer *)table
                            withNSString:(NSString *)key
                                 withInt:(int)column
                             withBoolean:(BOOL)fireAction;
- (void)reset;
- (void)copyAllFieldsTo:(ComSparsewareBellavistaaResultsManager *)other;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, currentView_, ComSparsewareBellavistaResultsViewEnum *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, dataTable_, RARETableViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, spreadsheetTable_, RARETableViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, namePrefix_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, chartHandler_, ComSparsewareBellavistaaChartHandler *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, transitionAnimation_, id<RAREiTransitionAnimator>)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, originalRows_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, itemCounts_, JavaUtilLinkedHashMap *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, itemDates_, IOSObjectArray *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, itemDatesSet_, JavaUtilLinkedHashSet *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, keyPath_, ComSparsewareBellavistaActionPath *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, dateContext_, id)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, scriptClassName_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager, chartableItems_, JavaUtilHashMap *)

@interface ComSparsewareBellavistaaResultsManager_$1 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaaResultsManager *this$0_;
  RARETableViewer *val$table_;
  RAREWindowViewer *val$w_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaaResultsManager:(ComSparsewareBellavistaaResultsManager *)outer$
                                 withRARETableViewer:(RARETableViewer *)capture$0
                                withRAREWindowViewer:(RAREWindowViewer *)capture$1;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$1, this$0_, ComSparsewareBellavistaaResultsManager *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$1, val$table_, RARETableViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$1, val$w_, RAREWindowViewer *)

@interface ComSparsewareBellavistaaResultsManager_$2 : RAREaWorkerTask {
 @public
  ComSparsewareBellavistaaResultsManager *this$0_;
  NSString *val$key_;
  RAREWindowViewer *val$w_;
  RARETableViewer *val$table_;
  RAREStackPaneViewer *val$sp_;
  JavaLangBoolean *val$forward_;
  BOOL val$horizontal_;
}

- (id)compute;
- (void)finishWithId:(id)result;
- (id)initWithComSparsewareBellavistaaResultsManager:(ComSparsewareBellavistaaResultsManager *)outer$
                                        withNSString:(NSString *)capture$0
                                withRAREWindowViewer:(RAREWindowViewer *)capture$1
                                 withRARETableViewer:(RARETableViewer *)capture$2
                             withRAREStackPaneViewer:(RAREStackPaneViewer *)capture$3
                                 withJavaLangBoolean:(JavaLangBoolean *)capture$4
                                         withBoolean:(BOOL)capture$5;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$2, this$0_, ComSparsewareBellavistaaResultsManager *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$2, val$key_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$2, val$w_, RAREWindowViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$2, val$table_, RARETableViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$2, val$sp_, RAREStackPaneViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$2, val$forward_, JavaLangBoolean *)

@interface ComSparsewareBellavistaaResultsManager_$3 : NSObject < JavaLangRunnable > {
 @public
  RARETableViewer *val$table_;
  int val$index_;
}

- (void)run;
- (id)initWithRARETableViewer:(RARETableViewer *)capture$0
                      withInt:(int)capture$1;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$3, val$table_, RARETableViewer *)

@interface ComSparsewareBellavistaaResultsManager_$4 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaaResultsManager *this$0_;
  RARETableViewer *val$table_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaaResultsManager:(ComSparsewareBellavistaaResultsManager *)outer$
                                 withRARETableViewer:(RARETableViewer *)capture$0;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$4, this$0_, ComSparsewareBellavistaaResultsManager *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$4, val$table_, RARETableViewer *)

@interface ComSparsewareBellavistaaResultsManager_$5 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaaResultsManager *this$0_;
  RARETableViewer *val$table_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaaResultsManager:(ComSparsewareBellavistaaResultsManager *)outer$
                                 withRARETableViewer:(RARETableViewer *)capture$0;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$5, this$0_, ComSparsewareBellavistaaResultsManager *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaaResultsManager_$5, val$table_, RARETableViewer *)

#endif // _ComSparsewareBellavistaaResultsManager_H_
