//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/CardStack.java
//
//  Created by decoteaud on 3/14/16.
//

#ifndef _CCPBVCardStack_H_
#define _CCPBVCardStack_H_

@class JavaUtilEventObject;
@class RAREStackPaneViewer;
@class RARETabPaneViewer;
@protocol RAREiPlatformIcon;
@protocol RAREiViewer;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/iFunctionCallback.h"
#include "com/appnativa/rare/ui/iEventHandler.h"
#include "java/lang/Runnable.h"

#define CCPBVCardStack_GO_DOWN 1
#define CCPBVCardStack_GO_LEFT 2
#define CCPBVCardStack_GO_RIGHT 3
#define CCPBVCardStack_GO_UP 0

@interface CCPBVCardStack : NSObject < RAREiEventHandler, RAREiFunctionCallback > {
 @public
  id<RAREiPlatformIcon> bundleIcon_;
  long long int lastKeyTime_;
  BOOL switching_;
  int flingVelocityThreshold_;
  int keyTimeThreshold_;
}

+ (int)GO_DOWN;
+ (int)GO_LEFT;
+ (int)GO_RIGHT;
+ (int)GO_UP;
+ (int)pinDigitCount;
+ (int *)pinDigitCountRef;
- (id)init;
+ (int)getPinDigitCount;
- (void)drillDownWithRAREiViewer:(id<RAREiViewer>)v;
- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (void)goUpWithRAREiWidget:(id<RAREiWidget>)widget;
- (void)onChangeEventWithNSString:(NSString *)eventName
                  withRAREiWidget:(id<RAREiWidget>)widget
          withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onConfigurePinValueWithNSString:(NSString *)eventName
                        withRAREiWidget:(id<RAREiWidget>)widget
                withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onEventWithNSString:(NSString *)eventName
            withRAREiWidget:(id<RAREiWidget>)widget
    withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onFlingEventWithNSString:(NSString *)eventName
                 withRAREiWidget:(id<RAREiWidget>)widget
         withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onKeyUpEventWithNSString:(NSString *)eventName
                 withRAREiWidget:(id<RAREiWidget>)widget
         withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onTabPaneConfiguredWithNSString:(NSString *)eventName
                        withRAREiWidget:(id<RAREiWidget>)widget
                withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onTapEventWithNSString:(NSString *)eventName
               withRAREiWidget:(id<RAREiWidget>)widget
       withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)goWithRAREiWidget:(id<RAREiWidget>)widget
                  withInt:(int)direction;
- (void)switchToWithRAREStackPaneViewer:(RAREStackPaneViewer *)sp
                                withInt:(int)index;
- (void)switchToWithRARETabPaneViewer:(RARETabPaneViewer *)tp
                              withInt:(int)index;
- (void)copyAllFieldsTo:(CCPBVCardStack *)other;
@end

J2OBJC_FIELD_SETTER(CCPBVCardStack, bundleIcon_, id<RAREiPlatformIcon>)

typedef CCPBVCardStack ComSparsewareBellavistaCardStack;

@interface CCPBVCardStack_$1 : NSObject < JavaLangRunnable > {
 @public
  CCPBVCardStack *this$0_;
  int val$direction_;
  RARETabPaneViewer *val$tp_;
  id<RAREiWidget> val$widget_;
  RAREStackPaneViewer *val$sp_;
}

- (void)run;
- (id)initWithCCPBVCardStack:(CCPBVCardStack *)outer$
                     withInt:(int)capture$0
       withRARETabPaneViewer:(RARETabPaneViewer *)capture$1
             withRAREiWidget:(id<RAREiWidget>)capture$2
     withRAREStackPaneViewer:(RAREStackPaneViewer *)capture$3;
@end

J2OBJC_FIELD_SETTER(CCPBVCardStack_$1, this$0_, CCPBVCardStack *)
J2OBJC_FIELD_SETTER(CCPBVCardStack_$1, val$tp_, RARETabPaneViewer *)
J2OBJC_FIELD_SETTER(CCPBVCardStack_$1, val$widget_, id<RAREiWidget>)
J2OBJC_FIELD_SETTER(CCPBVCardStack_$1, val$sp_, RAREStackPaneViewer *)

@interface CCPBVCardStack_$2 : NSObject < RAREiFunctionCallback > {
 @public
  RAREStackPaneViewer *val$sp_;
  int val$index_;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (id)initWithRAREStackPaneViewer:(RAREStackPaneViewer *)capture$0
                          withInt:(int)capture$1;
@end

J2OBJC_FIELD_SETTER(CCPBVCardStack_$2, val$sp_, RAREStackPaneViewer *)

@interface CCPBVCardStack_$3 : NSObject < RAREiFunctionCallback > {
 @public
  RARETabPaneViewer *val$tp_;
  int val$index_;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue;
- (id)initWithRARETabPaneViewer:(RARETabPaneViewer *)capture$0
                        withInt:(int)capture$1;
@end

J2OBJC_FIELD_SETTER(CCPBVCardStack_$3, val$tp_, RARETabPaneViewer *)

#endif // _CCPBVCardStack_H_
