//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/CollectionManager.java
//
//  Created by decoteaud on 3/12/15.
//

#ifndef _ComSparsewareBellavistaCollectionManager_H_
#define _ComSparsewareBellavistaCollectionManager_H_

@class JavaUtilHashMap;
@class JavaUtilHashSet;
@class RAREActionLink;
@class RARERenderableDataItem;
@class RAREUTJSONObject;
@class RAREWindowViewer;
@protocol RAREiDataCollection;
@protocol RAREiPlatformIcon;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "java/lang/Runnable.h"

@interface ComSparsewareBellavistaCollectionManager : NSObject < JavaLangRunnable > {
 @public
  int updateInterval_;
  long long int lastUpdate_;
  int quarterTime_;
  JavaUtilHashSet *sounds_;
  JavaUtilHashMap *collections_;
  BOOL paused_;
  BOOL started_;
}

+ (ComSparsewareBellavistaCollectionManager *)instance;
+ (void)setInstance:(ComSparsewareBellavistaCollectionManager *)instance;
- (id)init;
- (void)startPolling;
- (void)stopPolling;
- (void)updateUI;
- (void)clear;
- (id<RAREiDataCollection>)getCollectionWithNSString:(NSString *)name;
- (void)refreshNow;
- (void)run;
- (void)update;
- (BOOL)updateCollectionWithRAREWindowViewer:(RAREWindowViewer *)w
                                withNSString:(NSString *)name
                        withRAREUTJSONObject:(RAREUTJSONObject *)o;
- (void)updateUIWithRAREWindowViewer:(RAREWindowViewer *)w
                        withNSString:(NSString *)name
                withRAREUTJSONObject:(RAREUTJSONObject *)o
                 withJavaUtilHashSet:(JavaUtilHashSet *)sounds;
+ (ComSparsewareBellavistaCollectionManager *)getInstance;
- (void)copyAllFieldsTo:(ComSparsewareBellavistaCollectionManager *)other;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager, sounds_, JavaUtilHashSet *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager, collections_, JavaUtilHashMap *)

@interface ComSparsewareBellavistaCollectionManager_PatientList : NSObject {
 @public
  id<RAREiDataCollection> collection_;
  NSString *title_;
  NSString *listPath_;
  NSString *patientsPath_;
  BOOL containPatients_;
  NSString *name_;
}

- (BOOL)isContainsPatients;
- (RARERenderableDataItem *)createListItemWithBoolean:(BOOL)tabular
                                withRAREiPlatformIcon:(id<RAREiPlatformIcon>)listIcon;
- (NSString *)getCollectionHREF;
- (NSString *)getListHREFWithNSString:(NSString *)id_;
- (RAREActionLink *)getListLinkWithRAREiWidget:(id<RAREiWidget>)context
                                  withNSString:(NSString *)id_;
- (RAREActionLink *)getCollectionLinkWithRAREiWidget:(id<RAREiWidget>)context;
- (id)initWithRAREUTJSONObject:(RAREUTJSONObject *)list
          withRAREWindowViewer:(RAREWindowViewer *)w;
- (void)copyAllFieldsTo:(ComSparsewareBellavistaCollectionManager_PatientList *)other;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_PatientList, collection_, id<RAREiDataCollection>)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_PatientList, title_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_PatientList, listPath_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_PatientList, patientsPath_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_PatientList, name_, NSString *)

@interface ComSparsewareBellavistaCollectionManager_$1 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaCollectionManager *this$0_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaCollectionManager:(ComSparsewareBellavistaCollectionManager *)outer$;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_$1, this$0_, ComSparsewareBellavistaCollectionManager *)

@interface ComSparsewareBellavistaCollectionManager_$2 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaCollectionManager *this$0_;
  RAREWindowViewer *val$w_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaCollectionManager:(ComSparsewareBellavistaCollectionManager *)outer$
                                  withRAREWindowViewer:(RAREWindowViewer *)capture$0;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_$2, this$0_, ComSparsewareBellavistaCollectionManager *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaCollectionManager_$2, val$w_, RAREWindowViewer *)

#endif // _ComSparsewareBellavistaCollectionManager_H_
