//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/Consults.java
//
//  Created by decoteaud on 3/24/15.
//

#ifndef _CCPBVConsults_H_
#define _CCPBVConsults_H_

#import "JreEmulation.h"
#include "com/sparseware/bellavista/Notes.h"

@interface CCPBVConsults : CCPBVNotes {
}

- (id)init;
@end

typedef CCPBVConsults ComSparsewareBellavistaConsults;

#endif // _CCPBVConsults_H_
