//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/Document.java
//
//  Created by decoteaud on 3/12/15.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/appnativa/rare/FunctionCallbackWaiter.h"
#include "com/appnativa/rare/Platform.h"
#include "com/appnativa/rare/iCancelableFuture.h"
#include "com/appnativa/rare/iConstants.h"
#include "com/appnativa/rare/iFunctionCallback.h"
#include "com/appnativa/rare/iPlatformAppContext.h"
#include "com/appnativa/rare/net/ActionLink.h"
#include "com/appnativa/rare/net/JavaURLConnection.h"
#include "com/appnativa/rare/net/iMultipartMimeHandler.h"
#include "com/appnativa/rare/scripting/Functions.h"
#include "com/appnativa/rare/spot/GridPane.h"
#include "com/appnativa/rare/spot/Region.h"
#include "com/appnativa/rare/spot/SplitPane.h"
#include "com/appnativa/rare/ui/RenderableDataItem.h"
#include "com/appnativa/rare/ui/UIImageIcon.h"
#include "com/appnativa/rare/ui/UIScreen.h"
#include "com/appnativa/rare/ui/event/ActionEvent.h"
#include "com/appnativa/rare/ui/event/ChangeEvent.h"
#include "com/appnativa/rare/ui/event/iActionListener.h"
#include "com/appnativa/rare/ui/iPlatformComponent.h"
#include "com/appnativa/rare/util/DataItemCSVParser.h"
#include "com/appnativa/rare/util/DataItemParserHandler.h"
#include "com/appnativa/rare/viewer/CollapsiblePaneViewer.h"
#include "com/appnativa/rare/viewer/DocumentPaneViewer.h"
#include "com/appnativa/rare/viewer/GridPaneViewer.h"
#include "com/appnativa/rare/viewer/StackPaneViewer.h"
#include "com/appnativa/rare/viewer/TableViewer.h"
#include "com/appnativa/rare/viewer/ToolBarViewer.h"
#include "com/appnativa/rare/viewer/WebBrowser.h"
#include "com/appnativa/rare/viewer/WindowViewer.h"
#include "com/appnativa/rare/viewer/iContainer.h"
#include "com/appnativa/rare/viewer/iFormViewer.h"
#include "com/appnativa/rare/viewer/iTarget.h"
#include "com/appnativa/rare/viewer/iViewer.h"
#include "com/appnativa/rare/widget/iWidget.h"
#include "com/appnativa/spot/SPOTAny.h"
#include "com/appnativa/spot/SPOTBoolean.h"
#include "com/appnativa/spot/SPOTSet.h"
#include "com/appnativa/spot/iSPOTElement.h"
#include "com/appnativa/util/ObjectHolder.h"
#include "com/appnativa/util/StringCache.h"
#include "com/appnativa/util/iCancelable.h"
#include "com/appnativa/util/json/JSONObject.h"
#include "com/sparseware/bellavista/Document.h"
#include "com/sparseware/bellavista/Utils.h"
#include "com/sparseware/bellavista/external/aAttachmentHandler.h"
#include "java/io/StringReader.h"
#include "java/lang/Exception.h"
#include "java/lang/IllegalArgumentException.h"
#include "java/lang/Throwable.h"
#include "java/net/MalformedURLException.h"
#include "java/net/URL.h"
#include "java/util/ArrayList.h"
#include "java/util/Date.h"
#include "java/util/HashMap.h"
#include "java/util/List.h"
#include "java/util/Locale.h"

@implementation ComSparsewareBellavistaDocument

static RARERenderableDataItem * ComSparsewareBellavistaDocument__documentItem_;
static NSString * ComSparsewareBellavistaDocument_VIEWER_CALLBACK_ID_ = @"viewer";
static NSString * ComSparsewareBellavistaDocument_DOCUMENT_CALLBACK_ID_ = @"document";
static NSString * ComSparsewareBellavistaDocument_bodyOutOfBandText_;
static RARESPOTGridPane * ComSparsewareBellavistaDocument_genericContainerCfg_;
static RARESPOTGridPane * ComSparsewareBellavistaDocument_documentViewerCfg_;

+ (RARERenderableDataItem *)_documentItem {
  return ComSparsewareBellavistaDocument__documentItem_;
}

+ (NSString *)VIEWER_CALLBACK_ID {
  return ComSparsewareBellavistaDocument_VIEWER_CALLBACK_ID_;
}

+ (void)setVIEWER_CALLBACK_ID:(NSString *)VIEWER_CALLBACK_ID {
  ComSparsewareBellavistaDocument_VIEWER_CALLBACK_ID_ = VIEWER_CALLBACK_ID;
}

+ (NSString *)DOCUMENT_CALLBACK_ID {
  return ComSparsewareBellavistaDocument_DOCUMENT_CALLBACK_ID_;
}

+ (void)setDOCUMENT_CALLBACK_ID:(NSString *)DOCUMENT_CALLBACK_ID {
  ComSparsewareBellavistaDocument_DOCUMENT_CALLBACK_ID_ = DOCUMENT_CALLBACK_ID;
}

+ (NSString *)bodyOutOfBandText {
  return ComSparsewareBellavistaDocument_bodyOutOfBandText_;
}

+ (void)setBodyOutOfBandText:(NSString *)bodyOutOfBandText {
  ComSparsewareBellavistaDocument_bodyOutOfBandText_ = bodyOutOfBandText;
}

+ (RARESPOTGridPane *)genericContainerCfg {
  return ComSparsewareBellavistaDocument_genericContainerCfg_;
}

+ (void)setGenericContainerCfg:(RARESPOTGridPane *)genericContainerCfg {
  ComSparsewareBellavistaDocument_genericContainerCfg_ = genericContainerCfg;
}

+ (RARESPOTGridPane *)documentViewerCfg {
  return ComSparsewareBellavistaDocument_documentViewerCfg_;
}

+ (void)setDocumentViewerCfg:(RARESPOTGridPane *)documentViewerCfg {
  ComSparsewareBellavistaDocument_documentViewerCfg_ = documentViewerCfg;
}

- (id)initWithRAREiWidget:(id<RAREiWidget>)widget
       withRAREActionLink:(RAREActionLink *)link
             withNSString:(NSString *)id_ {
  if (self = [super init]) {
    self->documentLink_ = link;
    self->documentID_ = id_;
    contextWidget_Document_ = widget;
  }
  return self;
}

- (void)addAttachmentWithComSparsewareBellavistaDocument_DocumentItemTypeEnum:(ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)type
                                                             withJavaUtilDate:(JavaUtilDate *)date
                                                                 withNSString:(NSString *)title
                                                                 withNSString:(NSString *)href {
  [self addAttachmentWithComSparsewareBellavistaDocument_DocumentItemTypeEnum:type withJavaUtilDate:date withNSString:title withNSString:nil withNSString:nil withNSString:href];
}

- (void)addAttachmentWithComSparsewareBellavistaDocument_DocumentItemTypeEnum:(ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)type
                                                             withJavaUtilDate:(JavaUtilDate *)date
                                                                 withNSString:(NSString *)title
                                                                 withNSString:(NSString *)mimeType
                                                                 withNSString:(NSString *)body
                                                                 withNSString:(NSString *)href {
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  RARERenderableDataItem *row = [((RAREWindowViewer *) nil_chk(w)) createRowWithInt:5 withBoolean:YES];
  [((RARERenderableDataItem *) nil_chk([((RARERenderableDataItem *) nil_chk(row)) getWithInt:0])) setValueWithId:[((NSString *) nil_chk([((ComSparsewareBellavistaDocument_DocumentItemTypeEnum *) nil_chk(type)) description])) lowercaseStringWithJRELocale:[JavaUtilLocale US]]];
  [((RARERenderableDataItem *) nil_chk([row getWithInt:1])) setValueWithId:title];
  RARERenderableDataItem *item = [row getWithInt:2];
  [((RARERenderableDataItem *) nil_chk(item)) setTypeWithInt:RARERenderableDataItem_TYPE_DATETIME];
  [item setValueWithId:date];
  [((RARERenderableDataItem *) nil_chk([row getWithInt:3])) setValueWithId:@"false"];
  [((RARERenderableDataItem *) nil_chk([row getWithInt:4])) setValueWithId:href];
  ComSparsewareBellavistaDocument_DocumentItem *di = [[ComSparsewareBellavistaDocument_DocumentItem alloc] initWithNSString:body withNSString:mimeType withComSparsewareBellavistaDocument_DocumentItemTypeEnum:type];
  di->rowData_ = row;
  if (docAttachments_ == nil) {
    docAttachments_ = [[JavaUtilArrayList alloc] initWithInt:5];
  }
  [((id<JavaUtilList>) nil_chk(docAttachments_)) addWithId:di];
}

+ (void)staticInitialize {
  ComSparsewareBellavistaDocument_genericContainerCfg_ = (RARESPOTGridPane *) check_class_cast([((RAREWindowViewer *) nil_chk([RAREPlatform getWindowViewer])) createConfigurationObjectWithRAREActionLink:[[RAREActionLink alloc] initWithNSString:@"/generic_container.rml"]], [RARESPOTGridPane class]);
  ComSparsewareBellavistaDocument_documentViewerCfg_ = (RARESPOTGridPane *) check_class_cast([((RAREWindowViewer *) nil_chk([RAREPlatform getWindowViewer])) createConfigurationObjectWithRAREActionLink:[[RAREActionLink alloc] initWithNSString:@"/document_viewer.rml"]], [RARESPOTGridPane class]);
  RAREUTJSONObject *info = (RAREUTJSONObject *) check_class_cast([((id<RAREiPlatformAppContext>) nil_chk([RAREPlatform getAppContext])) getDataWithId:@"notesInfo"], [RAREUTJSONObject class]);
  ComSparsewareBellavistaDocument_bodyOutOfBandText_ = [((RAREUTJSONObject *) nil_chk(info)) optStringWithNSString:@"bodyOutOfBandText" withNSString:@""];
  if ([((NSString *) nil_chk(ComSparsewareBellavistaDocument_bodyOutOfBandText_)) sequenceLength] == 0) {
    ComSparsewareBellavistaDocument_bodyOutOfBandText_ = nil;
  }
}

- (id)compute {
  RAREActionLink *link = documentLink_;
  @try {
    if (![((RAREActionLink *) nil_chk(link)) isMultipartDocument]) {
      NSString *type = [link getContentType];
      NSString *data = [link getContentAsString];
      if ([ComSparsewareBellavistaUtils isDemo] && [((NSString *) nil_chk(data)) contains:@"SIRF_MULTIPART_BOUNDARY_PART"]) {
        link = [[RAREActionLink alloc] initWithNSString:data withNSString:@"multipart/mixed; boundary=\"__FF00_SIRF_MULTIPART_BOUNDARY_PART_OOFF__\""];
        [link setContextWithRAREiWidget:contextWidget_Document_];
      }
      else {
        mainDocument_ = [[ComSparsewareBellavistaDocument_DocumentItem alloc] initWithNSString:data withNSString:type withComSparsewareBellavistaDocument_DocumentItemTypeEnum:[ComSparsewareBellavistaDocument_DocumentItemTypeEnum DOCUMENT]];
        [self setMainDocumentInfoWithJavaUtilDate:documentDate_ withNSString:documentTitle_];
        return nil;
      }
    }
    id<RAREiMultipartMimeHandler_iMultipart> mp = [link getFirstPartWithRAREiWidget:contextWidget_Document_];
    int i = 0;
    NSString *s = [((id<RAREiMultipartMimeHandler_iMultipart>) nil_chk(mp)) getPreamble];
    id<JavaUtilList> items = nil;
    id<JavaUtilList> docs = [[JavaUtilArrayList alloc] initWithInt:5];
    if (s != nil) {
      s = [s trim];
      if ([((NSString *) nil_chk(s)) sequenceLength] != 0) {
        RAREDataItemParserHandler *ph = [[RAREDataItemParserHandler alloc] initWithRAREiWidget:contextWidget_Document_];
        RAREDataItemCSVParser *p = [[RAREDataItemCSVParser alloc] initWithJavaIoReader:[[JavaIoStringReader alloc] initWithNSString:s] withChar:[ComSparsewareBellavistaUtils colSeparator] withChar:[ComSparsewareBellavistaUtils ldSeparator]];
        [p parseWithRAREiWidget:contextWidget_Document_ withInt:-1 withRAREiDataItemParserCallback:ph];
        items = [ph getListEx];
      }
    }
    RARERenderableDataItem *row;
    int len = (items == nil) ? 0 : [items size];
    while (mp != nil) {
      ComSparsewareBellavistaDocument_DocumentItem *doc = [[ComSparsewareBellavistaDocument_DocumentItem alloc] init];
      doc->mimeType_ = [mp getContentType];
      doc->itemBody_ = [mp getContentAsString];
      if (i < len) {
        row = [((id<JavaUtilList>) nil_chk(items)) getWithInt:i++];
        if (ComSparsewareBellavistaDocument_bodyOutOfBandText_ != nil && [((NSString *) nil_chk(doc->itemBody_)) hasPrefix:ComSparsewareBellavistaDocument_bodyOutOfBandText_]) {
          doc->itemBody_ = nil;
        }
        doc = [self processDocumentRowWithComSparsewareBellavistaDocument_DocumentItem:doc withRARERenderableDataItem:row];
      }
      if ((doc != nil) && (mainDocument_ != doc)) {
        [docs addWithId:doc];
      }
      mp = [mp nextPart];
    }
    while (i < len) {
      ComSparsewareBellavistaDocument_DocumentItem *doc = [[ComSparsewareBellavistaDocument_DocumentItem alloc] init];
      row = [((id<JavaUtilList>) nil_chk(items)) getWithInt:i++];
      (void) [self processDocumentRowWithComSparsewareBellavistaDocument_DocumentItem:doc withRARERenderableDataItem:row];
      [docs addWithId:doc];
    }
    if ((mainDocument_ == nil) && ([docs size] > 0)) {
      mainDocument_ = [docs removeWithInt:0];
    }
    if (((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(mainDocument_))->rowData_ == nil) {
      [self setMainDocumentInfoWithJavaUtilDate:documentDate_ withNSString:documentTitle_];
    }
    else {
      if (documentTitle_ != nil) {
        [((RARERenderableDataItem *) nil_chk([mainDocument_->rowData_ getWithInt:1])) setValueWithId:documentTitle_];
      }
      if (documentDate_ != nil) {
        [((RARERenderableDataItem *) nil_chk([mainDocument_->rowData_ getWithInt:2])) setValueWithId:documentDate_];
      }
    }
    if (docAttachments_ != nil) {
      [docAttachments_ addAllWithInt:0 withJavaUtilCollection:docs];
    }
    else {
      docAttachments_ = docs;
    }
  }
  @catch (JavaLangException *e) {
    return e;
  }
  @finally {
    [((RAREActionLink *) nil_chk(link)) close];
    if (link != documentLink_) {
      [((RAREActionLink *) nil_chk(documentLink_)) close];
    }
  }
  return nil;
}

- (void)dispose {
  if (mainDocument_ != nil) {
    [mainDocument_ dispose];
  }
  if (docAttachments_ != nil) {
    for (ComSparsewareBellavistaDocument_DocumentItem * __strong d in docAttachments_) {
      [((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(d)) dispose];
    }
    [docAttachments_ clear];
  }
  if (documentLink_ != nil) {
    [documentLink_ clear];
  }
  contextWidget_Document_ = nil;
  mainDocument_ = nil;
  docAttachments_ = nil;
  documentLink_ = nil;
  callback_Document_ = nil;
  self->window_ = nil;
}

- (void)finishWithId:(id)result {
  if (callback_Document_ != nil) {
    [callback_Document_ finishedWithBoolean:result != nil withId:result == nil ? self : result];
    callback_Document_ = nil;
  }
}

- (ComSparsewareBellavistaDocument_DocumentItem *)getAttachmentWithInt:(int)index {
  return [((id<JavaUtilList>) nil_chk(docAttachments_)) getWithInt:index];
}

- (int)getAttachmentCount {
  return docAttachments_ == nil ? 0 : [docAttachments_ size];
}

- (NSString *)getID {
  return documentID_;
}

- (void)load__WithRAREiFunctionCallback:(id<RAREiFunctionCallback>)cb {
  self->callback_Document_ = cb;
  (void) [((RAREWindowViewer *) nil_chk([RAREPlatform getWindowViewer])) spawnWithNSObjectArray:[IOSObjectArray arrayWithObjects:(id[]){ self } count:1 type:[IOSClass classWithClass:[NSObject class]]]];
}

- (void)loadAndPopulateViewerWithRAREActionLink:(RAREActionLink *)viewerLink {
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  RAREFunctionCallbackWaiter *waiter = [[RAREFunctionCallbackWaiter alloc] init];
  (void) [((RAREWindowViewer *) nil_chk(w)) createViewerWithRAREActionLink:viewerLink withRAREiFunctionCallback:[waiter createCallbackWithId:ComSparsewareBellavistaDocument_VIEWER_CALLBACK_ID_]];
  [self load__WithRAREiFunctionCallback:[waiter createCallbackWithId:ComSparsewareBellavistaDocument_DOCUMENT_CALLBACK_ID_]];
  id<RAREiFunctionCallback> cb = [[ComSparsewareBellavistaDocument_$1 alloc] initWithComSparsewareBellavistaDocument:self withRAREActionLink:viewerLink withRAREWindowViewer:w];
  [w showWaitCursor];
  [waiter startWaitingWithRAREiFunctionCallback:cb];
}

- (void)loadAndPopulateViewerWithRAREiContainer:(id<RAREiContainer>)fv {
  id<RAREiFunctionCallback> cb = [[ComSparsewareBellavistaDocument_$2 alloc] initWithComSparsewareBellavistaDocument:self withRAREiContainer:fv];
  [self load__WithRAREiFunctionCallback:cb];
}

- (void)populateViewerWithRAREiContainer:(id<RAREiContainer>)fv {
  [((id<RAREiContainer>) nil_chk(fv)) setLinkedDataWithId:self];
  [self populateViewerWithRAREiContainer:fv withComSparsewareBellavistaDocument_DocumentItem:mainDocument_];
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  RARECollapsiblePaneViewer *cpv = (RARECollapsiblePaneViewer *) check_class_cast([fv getWidgetWithNSString:@"attachments"], [RARECollapsiblePaneViewer class]);
  if (cpv != nil) {
    RARETableViewer *table = (RARETableViewer *) check_class_cast([cpv getWidget], [RARETableViewer class]);
    id<RAREiActionListener> al = [[ComSparsewareBellavistaDocument_AttachmentActionListener alloc] init];
    [((RARETableViewer *) nil_chk(table)) clear];
    [table setActionListenerWithRAREiActionListener:al];
    int len = [self getAttachmentCount];
    [((id<RAREiTarget>) nil_chk([cpv getTarget])) setVisibleWithBoolean:len > 0];
    if (len > 0) {
      [cpv setTitleTextWithJavaLangCharSequence:[((RAREWindowViewer *) nil_chk(w)) getStringWithNSString:@"bv.format.attachments_spec" withNSObjectArray:[IOSObjectArray arrayWithObjects:(id[]){ [RAREUTStringCache valueOfWithInt:len] } count:1 type:[IOSClass classWithClass:[NSObject class]]]]];
      [cpv setActionListenerWithRAREiActionListener:al];
      [((RARERenderableDataItem *) nil_chk([((RARERenderableDataItem *) nil_chk(((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(mainDocument_))->rowData_)) getWithInt:1])) setValueWithId:[w getStringWithNSString:@"bv.text.master_document"]];
      BOOL hasDate = NO;
      for (int i = 0; i < len; i++) {
        ComSparsewareBellavistaDocument_DocumentItem *item = [((id<JavaUtilList>) nil_chk(docAttachments_)) getWithInt:i];
        if (((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(item))->rowData_ != nil) {
          [table addExWithRARERenderableDataItem:item->rowData_];
          if ([item hasDate]) {
            hasDate = YES;
          }
        }
      }
      if ([RAREUIScreen isMediumDensity]) {
        [table addExWithRARERenderableDataItem:mainDocument_->rowData_];
      }
      [table setColumnVisibleWithInt:2 withBoolean:hasDate];
      [table refreshItems];
    }
  }
}

- (void)populateViewerWithRAREiContainer:(id<RAREiContainer>)fv
withComSparsewareBellavistaDocument_DocumentItem:(ComSparsewareBellavistaDocument_DocumentItem *)doc {
  @try {
    RARERenderableDataItem *row = ((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(doc))->rowData_;
    id<RAREiWidget> field;
    field = [((id<RAREiContainer>) nil_chk(fv)) getWidgetWithNSString:@"documentDate"];
    NSString *s;
    if (field != nil) {
      s = row == nil ? @"" : [RAREFunctions convertDateTimeWithRAREiWidget:field withId:[((RARERenderableDataItem *) nil_chk([row getWithInt:2])) getValue]];
      [field setValueWithId:s];
    }
    field = [fv getWidgetWithNSString:@"documentTitle"];
    if (field != nil) {
      s = doc->itemTitle_;
      if (s == nil && row != nil) {
        s = [((RARERenderableDataItem *) nil_chk([row getWithInt:1])) description];
      }
      [field setValueWithId:s == nil ? @"" : s];
    }
    field = [fv getWidgetWithNSString:@"extraHeaderDetail"];
    if (field != nil) {
      s = @"";
      if ((row != nil) && ([row size] > 4)) {
        s = [field getValueAsString];
        if ((s != nil) && ([s sequenceLength] != 0)) {
          NSString *title = (NSString *) check_class_cast([((RARERenderableDataItem *) nil_chk([row getWithInt:4])) getValue], [NSString class]);
          s = [NSString formatWithNSString:s withNSObjectArray:[IOSObjectArray arrayWithObjects:(id[]){ title } count:1 type:[IOSClass classWithClass:[NSObject class]]]];
        }
        else {
          s = (NSString *) check_class_cast([((RARERenderableDataItem *) nil_chk([row getWithInt:4])) getValue], [NSString class]);
        }
      }
      [field setValueWithId:s];
    }
    id<RAREiViewer> v = (id<RAREiViewer>) check_protocol_cast([fv getWidgetWithNSString:@"documentDetail"], @protocol(RAREiViewer));
    if (v != nil) {
      BOOL html = NO;
      if ((doc->mimeType_ != nil) && [doc->mimeType_ hasPrefix:[RAREiConstants HTML_MIME_TYPE]]) {
        html = YES;
      }
      if ([(id) v isKindOfClass:[RAREDocumentPaneViewer class]]) {
        [((RAREDocumentPaneViewer *) check_class_cast(v, [RAREDocumentPaneViewer class])) setTextWithNSString:doc->itemBody_ withBoolean:html];
      }
      else if ([(id) v isKindOfClass:[RAREWebBrowser class]]) {
        s = doc->itemBody_;
        if (!html) {
          s = [NSString stringWithFormat:@"<html><body><pre>%@</pre></body></html>", s];
        }
        NSString *href = [RAREJavaURLConnection baseToExternalFormWithJavaNetURL:[((RAREActionLink *) nil_chk(documentLink_)) getURLWithRAREiWidget:contextWidget_Document_]];
        RAREWebBrowser *browser = (RAREWebBrowser *) check_class_cast(v, [RAREWebBrowser class]);
        if ([v getWidth] < 50) {
          NSString *data = s;
          NSString *url = href;
          [((id<RAREiPlatformComponent>) nil_chk([browser getContainerComponent])) addViewListenerWithRAREiViewListener:[[ComSparsewareBellavistaDocument_$3 alloc] initWithRAREWebBrowser:browser withNSString:url withNSString:data]];
        }
        else {
          [browser setHTMLWithNSString:href withNSString:s];
        }
      }
    }
  }
  @catch (JavaLangException *e) {
    [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:e];
  }
}

- (void)setMainDocumentWithNSString:(NSString *)body
                       withNSString:(NSString *)type
                   withJavaUtilDate:(JavaUtilDate *)date
                       withNSString:(NSString *)title {
  mainDocument_ = [[ComSparsewareBellavistaDocument_DocumentItem alloc] initWithNSString:body withNSString:type withComSparsewareBellavistaDocument_DocumentItemTypeEnum:[ComSparsewareBellavistaDocument_DocumentItemTypeEnum DOCUMENT]];
  [self setMainDocumentInfoWithJavaUtilDate:date withNSString:title];
}

- (void)setMainDocumentInfoWithJavaUtilDate:(JavaUtilDate *)date
                               withNSString:(NSString *)title {
  if (mainDocument_ != nil) {
    RARERenderableDataItem *row = [[RARERenderableDataItem alloc] init];
    [row addWithId:ComSparsewareBellavistaDocument__documentItem_];
    [row addWithId:[[RARERenderableDataItem alloc] initWithId:title]];
    [row addWithId:[[RARERenderableDataItem alloc] initWithId:date]];
    mainDocument_->rowData_ = row;
  }
  else {
    documentTitle_ = title;
    documentDate_ = date;
  }
}

- (ComSparsewareBellavistaDocument_DocumentItem *)processDocumentRowWithComSparsewareBellavistaDocument_DocumentItem:(ComSparsewareBellavistaDocument_DocumentItem *)doc
                                                                                          withRARERenderableDataItem:(RARERenderableDataItem *)row {
  if ([((RARERenderableDataItem *) nil_chk(row)) size] > 3) {
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum *type = [ComSparsewareBellavistaDocument_DocumentItemTypeEnum DOCUMENT];
    @try {
      NSString *s = [((RARERenderableDataItem *) nil_chk([row getWithInt:0])) description];
      NSString *custom = nil;
      int n = [((NSString *) nil_chk(s)) indexOf:':'];
      if (n != -1) {
        custom = [s substring:n + 1];
        s = [s substring:0 endIndex:n];
      }
      s = [((NSString *) nil_chk(s)) uppercaseStringWithJRELocale:[JavaUtilLocale US]];
      type = [ComSparsewareBellavistaDocument_DocumentItemTypeEnum valueOfWithNSString:s];
      if (type == [ComSparsewareBellavistaDocument_DocumentItemTypeEnum CUSTOM]) {
        ((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(doc))->customItemType_ = custom;
      }
    }
    @catch (JavaLangException *e) {
      [RAREPlatform ignoreExceptionWithNSString:nil withJavaLangThrowable:e];
    }
    ((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(doc))->itemType_ = type;
    switch ([type ordinal]) {
      case ComSparsewareBellavistaDocument_DocumentItemType_DOCUMENT:
      if ([@"true" isEqual:[((RARERenderableDataItem *) nil_chk([row getWithInt:3])) getValue]]) {
        mainDocument_ = doc;
      }
      break;
      case ComSparsewareBellavistaDocument_DocumentItemType_IMAGE:
      [((RARERenderableDataItem *) nil_chk([row getWithInt:0])) setIconWithRAREiPlatformIcon:[((id<RAREiPlatformAppContext>) nil_chk([RAREPlatform getAppContext])) getResourceAsIconWithNSString:@"bv.icon.xray"]];
      break;
      default:
      break;
    }
    [((RARERenderableDataItem *) nil_chk([row getWithInt:2])) setTypeWithInt:RARERenderableDataItem_TYPE_DATETIME];
  }
  ((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(doc))->rowData_ = row;
  return doc;
}

+ (RAREGridPaneViewer *)createDocumentViewerWithRAREiContainer:(id<RAREiContainer>)parent
                                                   withBoolean:(BOOL)hasAttachments {
  RARESPOTRegion *r = (RARESPOTRegion *) check_class_cast([((RARESPOTGridPane *) nil_chk(ComSparsewareBellavistaDocument_documentViewerCfg_))->regions_ getExWithInt:[((SPOTSet *) nil_chk(ComSparsewareBellavistaDocument_documentViewerCfg_->regions_)) size] - 1], [RARESPOTRegion class]);
  r = (RARESPOTRegion *) check_class_cast([((SPOTSet *) nil_chk(((RARESPOTSplitPane *) nil_chk([((SPOTAny *) nil_chk(((RARESPOTRegion *) nil_chk(r))->viewer_)) getValue]))->regions_)) getExWithInt:[ComSparsewareBellavistaDocument_documentViewerCfg_->regions_ size] - 1], [RARESPOTRegion class]);
  [((SPOTBoolean *) nil_chk(((RARESPOTRegion *) nil_chk(r))->visible_)) setValueWithBoolean:hasAttachments];
  return (RAREGridPaneViewer *) check_class_cast([((RAREWindowViewer *) nil_chk([RAREPlatform getWindowViewer])) createViewerWithRAREiWidget:parent withRARESPOTWidget:ComSparsewareBellavistaDocument_documentViewerCfg_], [RAREGridPaneViewer class]);
}

+ (void)initialize {
  if (self == [ComSparsewareBellavistaDocument class]) {
    ComSparsewareBellavistaDocument__documentItem_ = [[RARERenderableDataItem alloc] initWithId:@"document"];
  }
}

- (void)copyAllFieldsTo:(ComSparsewareBellavistaDocument *)other {
  [super copyAllFieldsTo:other];
  other->callback_Document_ = callback_Document_;
  other->contextWidget_Document_ = contextWidget_Document_;
  other->docAttachments_ = docAttachments_;
  other->documentDate_ = documentDate_;
  other->documentID_ = documentID_;
  other->documentLink_ = documentLink_;
  other->documentTitle_ = documentTitle_;
  other->mainDocument_ = mainDocument_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "staticInitialize", NULL, "V", 0x8, "JavaLangException" },
    { "compute", NULL, "LNSObject", 0x1, NULL },
    { "getAttachmentWithInt:", NULL, "LComSparsewareBellavistaDocument_DocumentItem", 0x1, NULL },
    { "getID", NULL, "LNSString", 0x1, NULL },
    { "loadAndPopulateViewerWithRAREActionLink:", NULL, "V", 0x1, "JavaLangException" },
    { "processDocumentRowWithComSparsewareBellavistaDocument_DocumentItem:withRARERenderableDataItem:", NULL, "LComSparsewareBellavistaDocument_DocumentItem", 0x4, NULL },
    { "createDocumentViewerWithRAREiContainer:withBoolean:", NULL, "LRAREGridPaneViewer", 0x9, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "documentID_", NULL, 0x4, "LNSString" },
    { "documentLink_", NULL, 0x4, "LRAREActionLink" },
    { "docAttachments_", NULL, 0x4, "LJavaUtilList" },
    { "mainDocument_", NULL, 0x4, "LComSparsewareBellavistaDocument_DocumentItem" },
    { "contextWidget_Document_", "contextWidget", 0x4, "LRAREiWidget" },
    { "callback_Document_", "callback", 0x4, "LRAREiFunctionCallback" },
    { "_documentItem_", NULL, 0x1a, "LRARERenderableDataItem" },
    { "VIEWER_CALLBACK_ID_", NULL, 0xa, "LNSString" },
    { "DOCUMENT_CALLBACK_ID_", NULL, 0xa, "LNSString" },
    { "documentDate_", NULL, 0x0, "LJavaUtilDate" },
    { "documentTitle_", NULL, 0x0, "LNSString" },
    { "bodyOutOfBandText_", NULL, 0x8, "LNSString" },
    { "genericContainerCfg_", NULL, 0x8, "LRARESPOTGridPane" },
    { "documentViewerCfg_", NULL, 0x8, "LRARESPOTGridPane" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument = { "Document", "com.sparseware.bellavista", NULL, 0x1, 7, methods, 14, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument;
}

@end
@implementation ComSparsewareBellavistaDocument_DocumentItem

- (id)init {
  if (self = [super init]) {
    itemType_ = [ComSparsewareBellavistaDocument_DocumentItemTypeEnum DOCUMENT];
  }
  return self;
}

- (id)initWithNSString:(NSString *)body
          withNSString:(NSString *)mimeType
withComSparsewareBellavistaDocument_DocumentItemTypeEnum:(ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)itemType {
  if (self = [super init]) {
    itemType_ = [ComSparsewareBellavistaDocument_DocumentItemTypeEnum DOCUMENT];
    self->itemBody_ = body;
    self->mimeType_ = mimeType;
    self->itemType_ = itemType;
  }
  return self;
}

- (void)dispose {
  if (handler_ != nil) {
    [handler_ dispose];
  }
  if (rowData_ != nil) {
    [rowData_ clear];
  }
  handler_ = nil;
  rowData_ = nil;
}

- (JavaUtilDate *)getDate {
  if (rowData_ != nil) {
    return (JavaUtilDate *) check_class_cast([((RARERenderableDataItem *) nil_chk([rowData_ getWithInt:2])) getValue], [JavaUtilDate class]);
  }
  return nil;
}

- (NSString *)getHREF {
  if (rowData_ != nil) {
    RARERenderableDataItem *item = [rowData_ getItemExWithInt:4];
    if (item != nil) {
      return [item description];
    }
  }
  return nil;
}

- (NSString *)getDateString {
  if (rowData_ != nil) {
    return [((RARERenderableDataItem *) nil_chk([rowData_ getWithInt:2])) description];
  }
  return nil;
}

- (ComSparsewareBellavistaExternalaAttachmentHandler *)getHandler {
  if (handler_ == nil) {
    handler_ = [ComSparsewareBellavistaUtils getAttachmentHandlerWithComSparsewareBellavistaDocument_DocumentItemTypeEnum:itemType_];
  }
  return handler_;
}

- (NSString *)getTitle {
  if (itemTitle_ == nil) {
    if (rowData_ != nil) {
      itemTitle_ = [((RARERenderableDataItem *) nil_chk([rowData_ getWithInt:1])) description];
    }
    else {
      itemTitle_ = @"";
    }
  }
  return itemTitle_;
}

- (BOOL)hasDate {
  RARERenderableDataItem *item = [((RARERenderableDataItem *) nil_chk(rowData_)) getItemExWithInt:2];
  return item != nil && [item getValue] != nil;
}

- (NSString *)description {
  return itemBody_;
}

- (void)copyAllFieldsTo:(ComSparsewareBellavistaDocument_DocumentItem *)other {
  [super copyAllFieldsTo:other];
  other->customItemType_ = customItemType_;
  other->handler_ = handler_;
  other->itemBody_ = itemBody_;
  other->itemTitle_ = itemTitle_;
  other->itemType_ = itemType_;
  other->mimeType_ = mimeType_;
  other->rowData_ = rowData_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "getDate", NULL, "LJavaUtilDate", 0x1, NULL },
    { "getHREF", NULL, "LNSString", 0x1, NULL },
    { "getDateString", NULL, "LNSString", 0x1, NULL },
    { "getHandler", NULL, "LComSparsewareBellavistaExternalaAttachmentHandler", 0x1, NULL },
    { "getTitle", NULL, "LNSString", 0x1, NULL },
    { "hasDate", NULL, "Z", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "itemType_", NULL, 0x1, "LComSparsewareBellavistaDocument_DocumentItemTypeEnum" },
    { "itemBody_", NULL, 0x1, "LNSString" },
    { "mimeType_", NULL, 0x1, "LNSString" },
    { "rowData_", NULL, 0x1, "LRARERenderableDataItem" },
    { "itemTitle_", NULL, 0x1, "LNSString" },
    { "customItemType_", NULL, 0x1, "LNSString" },
    { "handler_", NULL, 0x1, "LComSparsewareBellavistaExternalaAttachmentHandler" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_DocumentItem = { "DocumentItem", "com.sparseware.bellavista", "Document", 0x9, 6, methods, 7, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument_DocumentItem;
}

@end

static ComSparsewareBellavistaDocument_DocumentItemTypeEnum *ComSparsewareBellavistaDocument_DocumentItemTypeEnum_DOCUMENT;
static ComSparsewareBellavistaDocument_DocumentItemTypeEnum *ComSparsewareBellavistaDocument_DocumentItemTypeEnum_IMAGE;
static ComSparsewareBellavistaDocument_DocumentItemTypeEnum *ComSparsewareBellavistaDocument_DocumentItemTypeEnum_AUDIO;
static ComSparsewareBellavistaDocument_DocumentItemTypeEnum *ComSparsewareBellavistaDocument_DocumentItemTypeEnum_VIDEO;
static ComSparsewareBellavistaDocument_DocumentItemTypeEnum *ComSparsewareBellavistaDocument_DocumentItemTypeEnum_CUSTOM;
IOSObjectArray *ComSparsewareBellavistaDocument_DocumentItemTypeEnum_values;

@implementation ComSparsewareBellavistaDocument_DocumentItemTypeEnum

+ (ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)DOCUMENT {
  return ComSparsewareBellavistaDocument_DocumentItemTypeEnum_DOCUMENT;
}
+ (ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)IMAGE {
  return ComSparsewareBellavistaDocument_DocumentItemTypeEnum_IMAGE;
}
+ (ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)AUDIO {
  return ComSparsewareBellavistaDocument_DocumentItemTypeEnum_AUDIO;
}
+ (ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)VIDEO {
  return ComSparsewareBellavistaDocument_DocumentItemTypeEnum_VIDEO;
}
+ (ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)CUSTOM {
  return ComSparsewareBellavistaDocument_DocumentItemTypeEnum_CUSTOM;
}

- (id)copyWithZone:(NSZone *)zone {
  return self;
}

- (id)initWithNSString:(NSString *)__name withInt:(int)__ordinal {
  return [super initWithNSString:__name withInt:__ordinal];
}

+ (void)initialize {
  if (self == [ComSparsewareBellavistaDocument_DocumentItemTypeEnum class]) {
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum_DOCUMENT = [[ComSparsewareBellavistaDocument_DocumentItemTypeEnum alloc] initWithNSString:@"DOCUMENT" withInt:0];
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum_IMAGE = [[ComSparsewareBellavistaDocument_DocumentItemTypeEnum alloc] initWithNSString:@"IMAGE" withInt:1];
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum_AUDIO = [[ComSparsewareBellavistaDocument_DocumentItemTypeEnum alloc] initWithNSString:@"AUDIO" withInt:2];
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum_VIDEO = [[ComSparsewareBellavistaDocument_DocumentItemTypeEnum alloc] initWithNSString:@"VIDEO" withInt:3];
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum_CUSTOM = [[ComSparsewareBellavistaDocument_DocumentItemTypeEnum alloc] initWithNSString:@"CUSTOM" withInt:4];
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum_values = [[IOSObjectArray alloc] initWithObjects:(id[]){ ComSparsewareBellavistaDocument_DocumentItemTypeEnum_DOCUMENT, ComSparsewareBellavistaDocument_DocumentItemTypeEnum_IMAGE, ComSparsewareBellavistaDocument_DocumentItemTypeEnum_AUDIO, ComSparsewareBellavistaDocument_DocumentItemTypeEnum_VIDEO, ComSparsewareBellavistaDocument_DocumentItemTypeEnum_CUSTOM, nil } count:5 type:[IOSClass classWithClass:[ComSparsewareBellavistaDocument_DocumentItemTypeEnum class]]];
  }
}

+ (IOSObjectArray *)values {
  return [IOSObjectArray arrayWithArray:ComSparsewareBellavistaDocument_DocumentItemTypeEnum_values];
}

+ (ComSparsewareBellavistaDocument_DocumentItemTypeEnum *)valueOfWithNSString:(NSString *)name {
  for (int i = 0; i < [ComSparsewareBellavistaDocument_DocumentItemTypeEnum_values count]; i++) {
    ComSparsewareBellavistaDocument_DocumentItemTypeEnum *e = ComSparsewareBellavistaDocument_DocumentItemTypeEnum_values->buffer_[i];
    if ([name isEqual:[e name]]) {
      return e;
    }
  }
  @throw [[JavaLangIllegalArgumentException alloc] initWithNSString:name];
  return nil;
}

+ (J2ObjcClassInfo *)__metadata {
  static const char *superclass_type_args[] = {"LComSparsewareBellavistaDocument_DocumentItemTypeEnum"};
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_DocumentItemTypeEnum = { "DocumentItemType", "com.sparseware.bellavista", "Document", 0x4019, 0, NULL, 0, NULL, 1, superclass_type_args};
  return &_ComSparsewareBellavistaDocument_DocumentItemTypeEnum;
}

@end
@implementation ComSparsewareBellavistaDocument_AttachmentActionListener

- (void)actionPerformedWithRAREActionEvent:(RAREActionEvent *)e {
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  RARETableViewer *table = (RARETableViewer *) check_class_cast([((RAREActionEvent *) nil_chk(e)) getWidget], [RARETableViewer class]);
  id<RAREiFormViewer> fv = [((RARETableViewer *) nil_chk(table)) getFormViewer];
  ComSparsewareBellavistaDocument *doc = (ComSparsewareBellavistaDocument *) check_class_cast([((id<RAREiFormViewer>) nil_chk(fv)) getLinkedData], [ComSparsewareBellavistaDocument class]);
  int n = [table getSelectedIndex];
  ComSparsewareBellavistaDocument_DocumentItem *item = [((ComSparsewareBellavistaDocument *) nil_chk(doc)) getAttachmentWithInt:n];
  {
    ComSparsewareBellavistaExternalaAttachmentHandler *handler;
    switch ([((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(item))->itemType_ ordinal]) {
      case ComSparsewareBellavistaDocument_DocumentItemType_DOCUMENT:
      if (item->itemBody_ == nil) {
        [self handleOutOfBandAttachmentWithComSparsewareBellavistaDocument:doc withRAREiFormViewer:fv withComSparsewareBellavistaDocument_DocumentItem:item];
      }
      else {
        [doc populateViewerWithRAREiContainer:fv withComSparsewareBellavistaDocument_DocumentItem:item];
      }
      break;
      default:
      handler = [item getHandler];
      if (handler == nil) {
        [w alertWithId:[((RAREWindowViewer *) nil_chk(w)) getStringWithNSString:@"bv.text.cant_view_attachment"]];
      }
      else {
        [((RAREWindowViewer *) nil_chk(w)) showWaitCursor];
        RAREStackPaneViewer *sp = (RAREStackPaneViewer *) check_class_cast([ComSparsewareBellavistaUtils getStackPaneViewerWithRAREiWidget:fv], [RAREStackPaneViewer class]);
        RAREGridPaneViewer *gp = (RAREGridPaneViewer *) check_class_cast([w createViewerWithRAREiWidget:sp withRARESPOTWidget:[ComSparsewareBellavistaDocument genericContainerCfg]], [RAREGridPaneViewer class]);
        n = [((RAREStackPaneViewer *) nil_chk(sp)) addViewerWithNSString:nil withRAREiViewer:gp];
        [sp switchToWithInt:n];
        [handler createViewerWithRAREiContainer:gp withComSparsewareBellavistaDocument:doc withComSparsewareBellavistaDocument_DocumentItem:item withRAREiFunctionCallback:[[ComSparsewareBellavistaDocument_AttachmentCallback alloc] initWithRAREGridPaneViewer:gp]];
      }
      break;
    }
  }
}

- (void)handleOutOfBandAttachmentWithComSparsewareBellavistaDocument:(ComSparsewareBellavistaDocument *)doc
                                                 withRAREiFormViewer:(id<RAREiFormViewer>)fv
                    withComSparsewareBellavistaDocument_DocumentItem:(ComSparsewareBellavistaDocument_DocumentItem *)item {
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  NSString *href = [((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(item)) getHREF];
  @try {
    NSString *id_ = href;
    int n = [((NSString *) nil_chk(href)) lastIndexOf:'/'];
    if (n != -1) {
      id_ = [href substring:n + 1];
    }
    n = [((NSString *) nil_chk(id_)) lastIndexOf:'.'];
    if (n == -1) {
      href = [NSString stringWithFormat:@"%@.html", href];
    }
    else {
      id_ = [id_ substring:0 endIndex:n];
    }
    RAREActionLink *link = [[RAREActionLink alloc] initWithJavaNetURL:[((id<RAREiFormViewer>) nil_chk(fv)) getURLWithNSString:href]];
    ComSparsewareBellavistaDocument *ndoc = [[ComSparsewareBellavistaDocument alloc] initWithRAREiWidget:fv withRAREActionLink:link withNSString:id_];
    [ndoc load__WithRAREiFunctionCallback:[[ComSparsewareBellavistaDocument_AttachmentActionListener_$1 alloc] initWithRAREWindowViewer:w withRAREiFormViewer:fv withComSparsewareBellavistaDocument:ndoc withComSparsewareBellavistaDocument_DocumentItem:item withComSparsewareBellavistaDocument:doc]];
    [((RAREWindowViewer *) nil_chk(w)) showWaitCursor];
  }
  @catch (JavaNetMalformedURLException *e) {
    [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:e];
  }
}

- (id)init {
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "handleOutOfBandAttachmentWithComSparsewareBellavistaDocument:withRAREiFormViewer:withComSparsewareBellavistaDocument_DocumentItem:", NULL, "V", 0x0, NULL },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_AttachmentActionListener = { "AttachmentActionListener", "com.sparseware.bellavista", "Document", 0x8, 1, methods, 0, NULL, 0, NULL};
  return &_ComSparsewareBellavistaDocument_AttachmentActionListener;
}

@end
@implementation ComSparsewareBellavistaDocument_AttachmentActionListener_$1

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue {
  [((RAREWindowViewer *) nil_chk(val$w_)) hideWaitCursor];
  if ([returnValue isKindOfClass:[JavaLangThrowable class]]) {
    [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:(JavaLangThrowable *) check_class_cast(returnValue, [JavaLangThrowable class])];
  }
  else if (canceled || [((id<RAREiFormViewer>) nil_chk(val$fv_)) isDisposed]) {
    return;
  }
  ((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(((ComSparsewareBellavistaDocument *) nil_chk(val$ndoc_))->mainDocument_))->rowData_ = ((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(val$item_))->rowData_;
  if ([val$ndoc_ getAttachmentCount] == 0) {
    [((ComSparsewareBellavistaDocument *) nil_chk(val$doc_)) populateViewerWithRAREiContainer:val$fv_ withComSparsewareBellavistaDocument_DocumentItem:val$ndoc_->mainDocument_];
  }
  else {
    RAREStackPaneViewer *sp = [ComSparsewareBellavistaUtils getStackPaneViewerWithRAREiWidget:val$fv_];
    RAREGridPaneViewer *gp = [ComSparsewareBellavistaDocument createDocumentViewerWithRAREiContainer:sp withBoolean:YES];
    id<RAREiWidget> field = [((RAREGridPaneViewer *) nil_chk(gp)) getWidgetWithNSString:@"backButton"];
    if (field != nil) {
      [field setVisibleWithBoolean:YES];
    }
    int pos = [((RAREStackPaneViewer *) nil_chk(sp)) addViewerWithNSString:nil withRAREiViewer:gp];
    [val$ndoc_ populateViewerWithRAREiContainer:gp];
    [sp switchToWithInt:pos];
  }
}

- (id)initWithRAREWindowViewer:(RAREWindowViewer *)capture$0
           withRAREiFormViewer:(id<RAREiFormViewer>)capture$1
withComSparsewareBellavistaDocument:(ComSparsewareBellavistaDocument *)capture$2
withComSparsewareBellavistaDocument_DocumentItem:(ComSparsewareBellavistaDocument_DocumentItem *)capture$3
withComSparsewareBellavistaDocument:(ComSparsewareBellavistaDocument *)capture$4 {
  val$w_ = capture$0;
  val$fv_ = capture$1;
  val$ndoc_ = capture$2;
  val$item_ = capture$3;
  val$doc_ = capture$4;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcFieldInfo fields[] = {
    { "val$w_", NULL, 0x1012, "LRAREWindowViewer" },
    { "val$fv_", NULL, 0x1012, "LRAREiFormViewer" },
    { "val$ndoc_", NULL, 0x1012, "LComSparsewareBellavistaDocument" },
    { "val$item_", NULL, 0x1012, "LComSparsewareBellavistaDocument_DocumentItem" },
    { "val$doc_", NULL, 0x1012, "LComSparsewareBellavistaDocument" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_AttachmentActionListener_$1 = { "$1", "com.sparseware.bellavista", "Document$AttachmentActionListener", 0x8000, 0, NULL, 5, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument_AttachmentActionListener_$1;
}

@end
@implementation ComSparsewareBellavistaDocument_AttachmentCallback

- (id)initWithRAREGridPaneViewer:(RAREGridPaneViewer *)gp {
  if (self = [super init]) {
    gridPane_ = gp;
  }
  return self;
}

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue {
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  [((RAREWindowViewer *) nil_chk(w)) hideWaitCursor];
  if (!canceled) {
    if ([returnValue isKindOfClass:[JavaLangThrowable class]]) {
      [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:(JavaLangThrowable *) check_class_cast(returnValue, [JavaLangThrowable class])];
    }
    else {
      RAREUTObjectHolder *oh = (RAREUTObjectHolder *) check_class_cast(returnValue, [RAREUTObjectHolder class]);
      ComSparsewareBellavistaDocument_DocumentItem *ditem = (ComSparsewareBellavistaDocument_DocumentItem *) check_class_cast(((RAREUTObjectHolder *) nil_chk(oh))->type_, [ComSparsewareBellavistaDocument_DocumentItem class]);
      ComSparsewareBellavistaExternalaAttachmentHandler *handler = (ComSparsewareBellavistaExternalaAttachmentHandler *) check_class_cast(oh->source_, [ComSparsewareBellavistaExternalaAttachmentHandler class]);
      id<RAREiViewer> v = (id<RAREiViewer>) check_protocol_cast(oh->value_, @protocol(RAREiViewer));
      RAREGridPaneViewer *gp = gridPane_;
      if ([((RAREGridPaneViewer *) nil_chk(gp)) isDisposed]) {
        [((id<RAREiViewer>) nil_chk(v)) dispose];
        return;
      }
      (void) [gp setViewerWithInt:1 withRAREiViewer:v];
      RAREToolBarViewer *tb = (RAREToolBarViewer *) check_class_cast([gp getWidgetWithNSString:@"genericToolbar"], [RAREToolBarViewer class]);
      if (tb != nil) {
        id<RAREiWidget> field = [tb getWidgetWithNSString:@"genericLabel"];
        if (field != nil) {
          NSString *s = [((ComSparsewareBellavistaDocument_DocumentItem *) nil_chk(ditem)) getTitle];
          NSString *date = [ditem getDateString];
          if (date != nil) {
            s = [NSString stringWithFormat:@"%@ - %@", s, date];
          }
          [field setValueWithId:s];
        }
        id<JavaUtilList> buttons = [((ComSparsewareBellavistaExternalaAttachmentHandler *) nil_chk(handler)) getToolbarWidgetsWithRAREiViewer:v];
        if (buttons != nil) {
          [tb addSeparator];
          for (id<RAREiWidget> __strong b in buttons) {
            [tb addWidgetWithRAREiWidget:b];
          }
        }
      }
    }
  }
}

- (void)copyAllFieldsTo:(ComSparsewareBellavistaDocument_AttachmentCallback *)other {
  [super copyAllFieldsTo:other];
  other->gridPane_ = gridPane_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "initWithRAREGridPaneViewer:", NULL, NULL, 0x0, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "gridPane_", NULL, 0x0, "LRAREGridPaneViewer" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_AttachmentCallback = { "AttachmentCallback", "com.sparseware.bellavista", "Document", 0x8, 1, methods, 1, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument_AttachmentCallback;
}

@end
@implementation ComSparsewareBellavistaDocument_$1

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue {
  @try {
    RAREUTObjectHolder *h = (RAREUTObjectHolder *) check_class_cast(returnValue, [RAREUTObjectHolder class]);
    JavaUtilHashMap *resultsMap = (JavaUtilHashMap *) check_class_cast(((RAREUTObjectHolder *) nil_chk(h))->value_, [JavaUtilHashMap class]);
    RAREFunctionCallbackWaiter_CallbackResult *vr = [((JavaUtilHashMap *) nil_chk(resultsMap)) getWithId:[ComSparsewareBellavistaDocument VIEWER_CALLBACK_ID]];
    RAREFunctionCallbackWaiter_CallbackResult *dr = [resultsMap getWithId:[ComSparsewareBellavistaDocument DOCUMENT_CALLBACK_ID]];
    if ([((RAREFunctionCallbackWaiter_CallbackResult *) nil_chk(vr)) resultIsError]) {
      [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:(JavaLangThrowable *) check_class_cast([vr getReturnValue], [JavaLangThrowable class])];
      return;
    }
    if ([((RAREFunctionCallbackWaiter_CallbackResult *) nil_chk(dr)) resultIsError]) {
      [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:(JavaLangThrowable *) check_class_cast([dr getReturnValue], [JavaLangThrowable class])];
      return;
    }
    id<RAREiViewer> v = (id<RAREiViewer>) check_protocol_cast([vr getContent], @protocol(RAREiViewer));
    [this$0_ populateViewerWithRAREiContainer:[((id<RAREiViewer>) nil_chk(v)) getFormViewer]];
    NSString *target = [((RAREActionLink *) nil_chk(val$viewerLink_)) getTargetName];
    if (target == nil) {
      target = [RAREiTarget TARGET_WORKSPACE];
    }
    if ([((NSString *) nil_chk([RAREiTarget TARGET_WORKSPACE])) isEqual:target]) {
      [ComSparsewareBellavistaUtils pushWorkspaceViewerWithRAREiViewer:v];
    }
    else {
      [((RAREWindowViewer *) nil_chk(val$w_)) activateViewerWithRAREiViewer:v withNSString:target];
    }
  }
  @finally {
    [((RAREWindowViewer *) nil_chk(val$w_)) hideWaitCursor];
  }
}

- (id)initWithComSparsewareBellavistaDocument:(ComSparsewareBellavistaDocument *)outer$
                           withRAREActionLink:(RAREActionLink *)capture$0
                         withRAREWindowViewer:(RAREWindowViewer *)capture$1 {
  this$0_ = outer$;
  val$viewerLink_ = capture$0;
  val$w_ = capture$1;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "LComSparsewareBellavistaDocument" },
    { "val$viewerLink_", NULL, 0x1012, "LRAREActionLink" },
    { "val$w_", NULL, 0x1012, "LRAREWindowViewer" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_$1 = { "$1", "com.sparseware.bellavista", "Document", 0x8000, 0, NULL, 3, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument_$1;
}

@end
@implementation ComSparsewareBellavistaDocument_$2

- (void)finishedWithBoolean:(BOOL)canceled
                     withId:(id)returnValue {
  if ([returnValue isKindOfClass:[JavaLangException class]]) {
    [ComSparsewareBellavistaUtils handleErrorWithJavaLangThrowable:(JavaLangThrowable *) check_class_cast(returnValue, [JavaLangThrowable class])];
  }
  else {
    [this$0_ populateViewerWithRAREiContainer:val$fv_];
  }
}

- (id)initWithComSparsewareBellavistaDocument:(ComSparsewareBellavistaDocument *)outer$
                           withRAREiContainer:(id<RAREiContainer>)capture$0 {
  this$0_ = outer$;
  val$fv_ = capture$0;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcFieldInfo fields[] = {
    { "this$0_", NULL, 0x1012, "LComSparsewareBellavistaDocument" },
    { "val$fv_", NULL, 0x1012, "LRAREiContainer" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_$2 = { "$2", "com.sparseware.bellavista", "Document", 0x8000, 0, NULL, 2, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument_$2;
}

@end
@implementation ComSparsewareBellavistaDocument_$3

- (void)viewResizedWithRAREChangeEvent:(RAREChangeEvent *)e {
  if (![((RAREWebBrowser *) nil_chk(val$browser_)) isDisposed] && [val$browser_ getWidth] > 50) {
    [((id<RAREiPlatformComponent>) nil_chk([val$browser_ getContainerComponent])) removeViewListenerWithRAREiViewListener:self];
    [val$browser_ setHTMLWithNSString:val$url_ withNSString:val$data_];
  }
}

- (BOOL)wantsResizeEvent {
  return YES;
}

- (id)initWithRAREWebBrowser:(RAREWebBrowser *)capture$0
                withNSString:(NSString *)capture$1
                withNSString:(NSString *)capture$2 {
  val$browser_ = capture$0;
  val$url_ = capture$1;
  val$data_ = capture$2;
  return [super init];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "wantsResizeEvent", NULL, "Z", 0x1, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "val$browser_", NULL, 0x1012, "LRAREWebBrowser" },
    { "val$url_", NULL, 0x1012, "LNSString" },
    { "val$data_", NULL, 0x1012, "LNSString" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaDocument_$3 = { "$3", "com.sparseware.bellavista", "Document", 0x8000, 1, methods, 3, fields, 0, NULL};
  return &_ComSparsewareBellavistaDocument_$3;
}

@end
