//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/iValueChecker.java
//
//  Created by decoteaud on 11/18/15.
//

#ifndef _CCPBViValueChecker_H_
#define _CCPBViValueChecker_H_

@class RARERenderableDataItem;

#import "JreEmulation.h"

@protocol CCPBViValueChecker < NSObject, JavaObject >
- (BOOL)checkRowWithRARERenderableDataItem:(RARERenderableDataItem *)row
                                   withInt:(int)index
                                   withInt:(int)expandableColumn
                                   withInt:(int)rowCount;
@end

#define ComSparsewareBellavistaIValueChecker CCPBViValueChecker

#endif // _CCPBViValueChecker_H_
