//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/ListPager.java
//
//  Created by decoteaud on 2/17/16.
//

#include "IOSClass.h"
#include "IOSObjectArray.h"
#include "com/appnativa/rare/Platform.h"
#include "com/appnativa/rare/exception/ApplicationException.h"
#include "com/appnativa/rare/net/ActionLink.h"
#include "com/appnativa/rare/viewer/WindowViewer.h"
#include "com/sparseware/bellavista/ListPager.h"
#include "com/sparseware/bellavista/MessageException.h"
#include "com/sparseware/bellavista/Utils.h"
#include "java/net/MalformedURLException.h"
#include "java/net/URL.h"
#include "java/util/ArrayList.h"

@implementation CCPBVListPager

- (id)init {
  return [super init];
}

- (RAREActionLink *)next {
  RAREActionLink *link = next__;
  next__ = nil;
  return link;
}

- (RAREActionLink *)previous {
  RAREActionLink *link = nil;
  if (stack_ != nil) {
    int pos = [stack_ size] - 2;
    link = (pos > -1) ? [stack_ getWithInt:pos] : nil;
    if (link != nil) {
      (void) [stack_ removeWithInt:pos];
      (void) [stack_ removeWithInt:pos];
    }
  }
  next__ = nil;
  return link;
}

+ (RAREActionLink *)createPagingLinkWithRAREActionLink:(RAREActionLink *)source
                                          withNSString:(NSString *)href {
  RAREActionLink *l = [[RAREActionLink alloc] initWithNSString:href];
  RAREWindowViewer *w = [RAREPlatform getWindowViewer];
  @try {
    if (![CCPBVUtils isSameServerWithJavaNetURL:[((RAREActionLink *) nil_chk(source)) getURLWithRAREUTiURLResolver:w] withJavaNetURL:[l getURLWithRAREUTiURLResolver:w]]) {
      NSString *server = [((JavaNetURL *) nil_chk([l getURLWithRAREUTiURLResolver:w])) description];
      @throw [[CCPBVMessageException alloc] initWithNSString:[((RAREWindowViewer *) nil_chk([RAREPlatform getWindowViewer])) getStringWithNSString:@"bv.text.redirect_error" withNSObjectArray:[IOSObjectArray arrayWithObjects:(id[]){ server } count:1 type:[IOSClass classWithClass:[NSObject class]]]] withBoolean:YES];
    }
  }
  @catch (JavaNetMalformedURLException *e) {
    @throw [[RAREApplicationException alloc] initWithJavaLangThrowable:e];
  }
  return l;
}

- (void)setNextWithRAREActionLink:(RAREActionLink *)next {
  self->next__ = next;
}

- (void)clear {
  next__ = nil;
  if (stack_ != nil) {
    [stack_ clear];
  }
}

- (void)addWithRAREActionLink:(RAREActionLink *)link {
  [((JavaUtilArrayList *) nil_chk([self getStack])) addWithId:link];
}

- (BOOL)hasNext {
  return next__ != nil;
}

- (BOOL)hasPrevious {
  return (stack_ == nil) ? NO : [stack_ size] > 1;
}

- (JavaUtilArrayList *)getStack {
  if (stack_ == nil) {
    stack_ = [[JavaUtilArrayList alloc] initWithInt:5];
  }
  return stack_;
}

- (void)copyAllFieldsTo:(CCPBVListPager *)other {
  [super copyAllFieldsTo:other];
  other->next__ = next__;
  other->stack_ = stack_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "next", NULL, "LRAREActionLink", 0x1, NULL },
    { "previous", NULL, "LRAREActionLink", 0x1, NULL },
    { "createPagingLinkWithRAREActionLink:withNSString:", NULL, "LRAREActionLink", 0x9, NULL },
    { "hasNext", NULL, "Z", 0x1, NULL },
    { "hasPrevious", NULL, "Z", 0x1, NULL },
    { "getStack", NULL, "LJavaUtilArrayList", 0x4, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "stack_", NULL, 0x4, "LJavaUtilArrayList" },
    { "next__", "next", 0x4, "LRAREActionLink" },
  };
  static J2ObjcClassInfo _CCPBVListPager = { "ListPager", "com.sparseware.bellavista", NULL, 0x1, 6, methods, 2, fields, 0, NULL};
  return &_CCPBVListPager;
}

@end
