//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/MessageException.java
//
//  Created by decoteaud on 3/14/16.
//

#ifndef _CCPBVMessageException_H_
#define _CCPBVMessageException_H_

@class JavaIoPrintWriter;
@class JavaLangThrowable;

#import "JreEmulation.h"
#include "java/lang/RuntimeException.h"

@interface CCPBVMessageException : JavaLangRuntimeException {
 @public
  BOOL fatal_;
  JavaLangThrowable *myCause_;
}

- (id)initWithNSString:(NSString *)msg;
- (id)initWithNSString:(NSString *)msg
           withBoolean:(BOOL)fatal;
- (BOOL)isFatal;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)e;
- (void)printStackTraceWithJavaIoPrintWriter:(JavaIoPrintWriter *)s;
- (void)copyAllFieldsTo:(CCPBVMessageException *)other;
@end

J2OBJC_FIELD_SETTER(CCPBVMessageException, myCause_, JavaLangThrowable *)

typedef CCPBVMessageException ComSparsewareBellavistaMessageException;

#endif // _CCPBVMessageException_H_
