//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/MessageException.java
//
//  Created by decoteaud on 11/18/15.
//

#include "com/sparseware/bellavista/MessageException.h"

@implementation CCPBVMessageException

- (id)initWithNSString:(NSString *)msg {
  return [super initWithNSString:msg];
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcClassInfo _CCPBVMessageException = { "MessageException", "com.sparseware.bellavista", NULL, 0x1, 0, NULL, 0, NULL, 0, NULL};
  return &_CCPBVMessageException;
}

@end
