//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/OrderManager.java
//
//  Created by decoteaud on 5/11/15.
//

#ifndef _CCPBVOrderManager_H_
#define _CCPBVOrderManager_H_

@class CCPBVActionPath;
@protocol JavaUtilMap;

#import "JreEmulation.h"

#define CCPBVOrderManager_ORDERING_STATE_DISCONTINUED 2
#define CCPBVOrderManager_ORDERING_STATE_FLAGGED 1
#define CCPBVOrderManager_ORDERING_STATE_REORDERED 4

@interface CCPBVOrderManager : NSObject {
}

+ (int)ORDERING_STATE_FLAGGED;
+ (int)ORDERING_STATE_DISCONTINUED;
+ (int)ORDERING_STATE_REORDERED;
+ (id<JavaUtilMap>)stateIcons;
+ (void)setStateIcons:(id<JavaUtilMap>)stateIcons;
- (id)init;
+ (BOOL)canChangePatientOrExitWithBoolean:(BOOL)exit
                      withCCPBVActionPath:(CCPBVActionPath *)path;
+ (BOOL)canExit;
+ (id<JavaUtilMap>)getStateIcons;
@end

typedef CCPBVOrderManager ComSparsewareBellavistaOrderManager;

#endif // _CCPBVOrderManager_H_
