//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/OrderManager.java
//
//  Created by decoteaud on 3/12/15.
//

#include "com/sparseware/bellavista/ActionPath.h"
#include "com/sparseware/bellavista/OrderManager.h"
#include "java/util/HashMap.h"
#include "java/util/Map.h"

@implementation ComSparsewareBellavistaOrderManager

static id<JavaUtilMap> ComSparsewareBellavistaOrderManager_stateIcons_;

+ (int)ORDERING_STATE_FLAGGED {
  return ComSparsewareBellavistaOrderManager_ORDERING_STATE_FLAGGED;
}

+ (int)ORDERING_STATE_DISCONTINUED {
  return ComSparsewareBellavistaOrderManager_ORDERING_STATE_DISCONTINUED;
}

+ (int)ORDERING_STATE_REORDERED {
  return ComSparsewareBellavistaOrderManager_ORDERING_STATE_REORDERED;
}

+ (id<JavaUtilMap>)stateIcons {
  return ComSparsewareBellavistaOrderManager_stateIcons_;
}

+ (void)setStateIcons:(id<JavaUtilMap>)stateIcons {
  ComSparsewareBellavistaOrderManager_stateIcons_ = stateIcons;
}

- (id)init {
  return [super init];
}

+ (BOOL)canChangePatientOrExitWithBoolean:(BOOL)exit
    withComSparsewareBellavistaActionPath:(ComSparsewareBellavistaActionPath *)path {
  return YES;
}

+ (BOOL)canExit {
  return YES;
}

+ (id<JavaUtilMap>)getStateIcons {
  if (ComSparsewareBellavistaOrderManager_stateIcons_ == nil) {
    ComSparsewareBellavistaOrderManager_stateIcons_ = [[JavaUtilHashMap alloc] initWithInt:3];
  }
  return ComSparsewareBellavistaOrderManager_stateIcons_;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "canChangePatientOrExitWithBoolean:withComSparsewareBellavistaActionPath:", NULL, "Z", 0x9, NULL },
    { "canExit", NULL, "Z", 0x9, NULL },
    { "getStateIcons", NULL, "LJavaUtilMap", 0x9, NULL },
  };
  static J2ObjcFieldInfo fields[] = {
    { "ORDERING_STATE_FLAGGED_", NULL, 0x19, "I" },
    { "ORDERING_STATE_DISCONTINUED_", NULL, 0x19, "I" },
    { "ORDERING_STATE_REORDERED_", NULL, 0x19, "I" },
    { "stateIcons_", NULL, 0xa, "LJavaUtilMap" },
  };
  static J2ObjcClassInfo _ComSparsewareBellavistaOrderManager = { "OrderManager", "com.sparseware.bellavista", NULL, 0x1, 3, methods, 4, fields, 0, NULL};
  return &_ComSparsewareBellavistaOrderManager;
}

@end
