//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/Orders.java
//
//  Created by decoteaud on 3/16/15.
//

#ifndef _ComSparsewareBellavistaOrders_H_
#define _ComSparsewareBellavistaOrders_H_

@class ComSparsewareBellavistaActionPath;
@class JavaUtilEventObject;
@class RAREActionEvent;
@class RAREActionLink;
@class RARETableViewer;
@class RAREUTJSONObject;
@protocol JavaUtilList;
@protocol RAREiContainer;
@protocol RAREiFormViewer;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/event/iActionListener.h"
#include "com/sparseware/bellavista/aResultsManager.h"
#include "java/lang/Runnable.h"

#define ComSparsewareBellavistaOrders_CATEGORY_NAME_POSITION 13
#define ComSparsewareBellavistaOrders_CLINICAL_CATEGORY_POSITION 14

@interface ComSparsewareBellavistaOrders : ComSparsewareBellavistaaResultsManager < RAREiActionListener > {
 @public
  int categorySortPosition_;
  BOOL hasClinicalCategories_;
  RAREUTJSONObject *statusColors_;
  NSString *endHtml_;
  NSString *startHtml_;
  NSString *endHtmlSC_;
  NSString *startHtmlSC_;
  BOOL appendDirections_;
  BOOL includeIVsInCategorizedMeds_;
  NSString *categorizedMedsTitle_;
  NSString *missingClinicalCategoryTitle_;
  NSString *missingCategoryTitle_;
  NSString *ivsCategoryID_;
  NSString *medsCategoryID_;
  NSString *cmedsCategoryID_;
  id<JavaUtilList> categorizedMeds_;
  BOOL categorizedMedsLoaded_;
  id<JavaUtilList> allOrders_;
}

+ (int)CATEGORY_NAME_POSITION;
+ (int)CLINICAL_CATEGORY_POSITION;
+ (int)SIG_COLUMN;
+ (int *)SIG_COLUMNRef;
+ (int)STATUS_COLUMN;
+ (int *)STATUS_COLUMNRef;
+ (int)SUMMARY_STATUS_COLUMN;
+ (int *)SUMMARY_STATUS_COLUMNRef;
- (id)init;
- (void)onDisposeWithNSString:(NSString *)eventName
              withRAREiWidget:(id<RAREiWidget>)widget
      withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)actionPerformedWithRAREActionEvent:(RAREActionEvent *)e;
- (void)onSummaryTableActionWithNSString:(NSString *)eventName
                         withRAREiWidget:(id<RAREiWidget>)widget
                 withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onTableActionWithNSString:(NSString *)eventName
                  withRAREiWidget:(id<RAREiWidget>)widget
          withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)dataParsedWithRAREiWidget:(id<RAREiWidget>)widget
                 withJavaUtilList:(id<JavaUtilList>)rows
               withRAREActionLink:(RAREActionLink *)link;
- (void)filterTableWithRARETableViewer:(RARETableViewer *)table
                          withNSString:(NSString *)filter;
- (void)processDataWithRARETableViewer:(RARETableViewer *)table
                      withJavaUtilList:(id<JavaUtilList>)rows;
- (void)reset;
- (void)updateCategoriesWithRAREiFormViewer:(id<RAREiFormViewer>)fv
                           withJavaUtilList:(id<JavaUtilList>)categories
                                    withInt:(int)selectedIndex;
- (void)updateTableWithRARETableViewer:(RARETableViewer *)table
                      withJavaUtilList:(id<JavaUtilList>)rows;
- (void)clearFormWithRAREiContainer:(id<RAREiContainer>)fv;
- (void)copyAllFieldsTo:(ComSparsewareBellavistaOrders *)other;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, statusColors_, RAREUTJSONObject *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, endHtml_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, startHtml_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, endHtmlSC_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, startHtmlSC_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, categorizedMedsTitle_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, missingClinicalCategoryTitle_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, missingCategoryTitle_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, ivsCategoryID_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, medsCategoryID_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, cmedsCategoryID_, NSString *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, categorizedMeds_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders, allOrders_, id<JavaUtilList>)

@interface ComSparsewareBellavistaOrders_$1 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaOrders *this$0_;
  RARETableViewer *val$table_;
  id<JavaUtilList> val$rows_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaOrders:(ComSparsewareBellavistaOrders *)outer$
                        withRARETableViewer:(RARETableViewer *)capture$0
                           withJavaUtilList:(id<JavaUtilList>)capture$1;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$1, this$0_, ComSparsewareBellavistaOrders *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$1, val$table_, RARETableViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$1, val$rows_, id<JavaUtilList>)

@interface ComSparsewareBellavistaOrders_$2 : NSObject < JavaLangRunnable > {
 @public
  ComSparsewareBellavistaOrders *this$0_;
  RARETableViewer *val$table_;
  id<JavaUtilList> val$categories_;
  int val$selectedIndex_;
  ComSparsewareBellavistaActionPath *val$path_;
}

- (void)run;
- (id)initWithComSparsewareBellavistaOrders:(ComSparsewareBellavistaOrders *)outer$
                        withRARETableViewer:(RARETableViewer *)capture$0
                           withJavaUtilList:(id<JavaUtilList>)capture$1
                                    withInt:(int)capture$2
      withComSparsewareBellavistaActionPath:(ComSparsewareBellavistaActionPath *)capture$3;
@end

J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$2, this$0_, ComSparsewareBellavistaOrders *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$2, val$table_, RARETableViewer *)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$2, val$categories_, id<JavaUtilList>)
J2OBJC_FIELD_SETTER(ComSparsewareBellavistaOrders_$2, val$path_, ComSparsewareBellavistaActionPath *)

#endif // _ComSparsewareBellavistaOrders_H_
