//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/Procedures.java
//
//  Created by decoteaud on 2/17/16.
//

#ifndef _CCPBVProcedures_H_
#define _CCPBVProcedures_H_

@class JavaUtilEventObject;
@class RAREActionEvent;
@protocol JavaUtilList;
@protocol RAREiContainer;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/appnativa/rare/ui/event/iActionListener.h"
#include "com/sparseware/bellavista/Notes.h"

@interface CCPBVProcedures : CCPBVNotes {
}

+ (int)STATUS_COLUMN;
+ (int *)STATUS_COLUMNRef;
- (id)init;
- (void)onCreatedWithNSString:(NSString *)eventName
              withRAREiWidget:(id<RAREiWidget>)widget
      withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onFinishedLoadingWithNSString:(NSString *)eventName
                      withRAREiWidget:(id<RAREiWidget>)widget
              withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)populateCardStackWithRAREiContainer:(id<RAREiContainer>)fv
                           withJavaUtilList:(id<JavaUtilList>)rows;
@end

typedef CCPBVProcedures ComSparsewareBellavistaProcedures;

@interface CCPBVProcedures_OrdersStackActionListener : NSObject < RAREiActionListener > {
 @public
  CCPBVProcedures *this$0_;
}

- (void)actionPerformedWithRAREActionEvent:(RAREActionEvent *)e;
- (id)initWithCCPBVProcedures:(CCPBVProcedures *)outer$;
@end

J2OBJC_FIELD_SETTER(CCPBVProcedures_OrdersStackActionListener, this$0_, CCPBVProcedures *)

#endif // _CCPBVProcedures_H_
