//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/TextFieldBorder.java
//
//  Created by decoteaud on 2/17/16.
//

#include "com/appnativa/rare/ui/UIColor.h"
#include "com/appnativa/rare/ui/UIInsets.h"
#include "com/appnativa/rare/ui/UIStroke.h"
#include "com/appnativa/rare/ui/border/UILineBorder.h"
#include "com/appnativa/rare/ui/border/aUILineBorder.h"
#include "com/appnativa/rare/ui/iPlatformComponent.h"
#include "com/appnativa/rare/ui/iPlatformGraphics.h"
#include "com/sparseware/bellavista/TextFieldBorder.h"

@implementation CCPBVTextFieldBorder

- (id)init {
  if (self = [super initWithRAREUIColor:[RAREaUILineBorder getDefaultLineColor]]) {
    noTop_ = YES;
  }
  return self;
}

- (void)paintWithRAREiPlatformGraphics:(id<RAREiPlatformGraphics>)g
                             withFloat:(float)x
                             withFloat:(float)y
                             withFloat:(float)width
                             withFloat:(float)height
                           withBoolean:(BOOL)last {
  if (last != [self isPaintLast]) {
    return;
  }
  RAREUIColor *color = [self getPaintColorWithRAREiPlatformComponent:[((id<RAREiPlatformGraphics>) nil_chk(g)) getComponent]];
  if ([((RAREUIColor *) nil_chk(color)) getAlpha] == 0) {
    return;
  }
  RAREUIStroke *stroke = [g getStroke];
  RAREUIColor *c = [g getColor];
  [g setColorWithRAREUIColor:color];
  if (lineStroke_ != nil) {
    [g setStrokeWithRAREUIStroke:lineStroke_];
  }
  else {
    [g setStrokeWidthWithFloat:thickness_];
  }
  if (insets_ == nil) {
    insets_ = [[RAREUIInsets alloc] init];
  }
  float left = x;
  float top = y;
  float right = x + width;
  float bottom = y + height;
  RAREUIInsets *in = [self calculateInsetsWithRAREUIInsets:insets_ withBoolean:NO];
  top = bottom - (height / 3);
  if (((RAREUIInsets *) nil_chk(in))->left_ > 0) {
    [g fillRectWithFloat:left withFloat:top withFloat:in->left_ withFloat:bottom - top];
  }
  if (in->bottom_ > 0) {
    [g fillRectWithFloat:left withFloat:bottom - in->bottom_ withFloat:right - left withFloat:in->bottom_];
  }
  if (in->right_ > 0) {
    [g fillRectWithFloat:right - in->right_ withFloat:top withFloat:in->right_ withFloat:bottom - top];
  }
  [g setStrokeWithRAREUIStroke:stroke];
  [g setColorWithRAREUIColor:c];
}

- (BOOL)usesPath {
  return NO;
}

+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "usesPath", NULL, "Z", 0x1, NULL },
  };
  static J2ObjcClassInfo _CCPBVTextFieldBorder = { "TextFieldBorder", "com.sparseware.bellavista", NULL, 0x1, 1, methods, 0, NULL, 0, NULL};
  return &_CCPBVTextFieldBorder;
}

@end
