//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: com/sparseware/bellavista/Vitals.java
//
//  Created by decoteaud on 3/12/15.
//

#ifndef _ComSparsewareBellavistaVitals_H_
#define _ComSparsewareBellavistaVitals_H_

@class JavaUtilEventObject;
@class RAREActionLink;
@class RAREChartDataItem;
@class RARERenderableDataItem;
@class RARESPOTChart;
@class RAREStackPaneViewer;
@class RARETableViewer;
@class RAREUTJSONObject;
@protocol JavaUtilList;
@protocol RAREiWidget;

#import "JreEmulation.h"
#include "com/sparseware/bellavista/aChartHandler.h"
#include "com/sparseware/bellavista/aResultsManager.h"
#include "com/sparseware/bellavista/iValueChecker.h"

@interface ComSparsewareBellavistaVitals : ComSparsewareBellavistaaResultsManager < ComSparsewareBellavistaiValueChecker > {
}

- (id)init;
- (NSString *)getSpeeedSheetColumnTitle;
- (void)onSummaryClickWithNSString:(NSString *)eventName
                   withRAREiWidget:(id<RAREiWidget>)widget
           withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)changeViewWithNSString:(NSString *)eventName
               withRAREiWidget:(id<RAREiWidget>)widget
       withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onShowComboChartWithNSString:(NSString *)eventName
                     withRAREiWidget:(id<RAREiWidget>)widget
             withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (BOOL)checkRowWithRARERenderableDataItem:(RARERenderableDataItem *)row
                                   withInt:(int)index
                                   withInt:(int)expandableColumn
                                   withInt:(int)rowCount;
- (void)onFinishedLoadingWithNSString:(NSString *)eventName
                      withRAREiWidget:(id<RAREiWidget>)widget
              withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)onChartsPanelLoadedWithNSString:(NSString *)eventName
                        withRAREiWidget:(id<RAREiWidget>)widget
                withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (void)selectVitalsWithNSString:(NSString *)eventName
                 withRAREiWidget:(id<RAREiWidget>)widget
         withJavaUtilEventObject:(JavaUtilEventObject *)event;
- (id<JavaUtilList>)createSpreadsheetRowsWithRARETableViewer:(RARETableViewer *)table;
- (void)processDataWithRARETableViewer:(RARETableViewer *)table
                      withJavaUtilList:(id<JavaUtilList>)rows;
- (void)showComboChartWithRAREStackPaneViewer:(RAREStackPaneViewer *)sp;
- (void)handlePathKeyWithRARETableViewer:(RARETableViewer *)table
                            withNSString:(NSString *)key
                                 withInt:(int)column
                             withBoolean:(BOOL)fireAction;
- (void)dataParsedWithRAREiWidget:(id<RAREiWidget>)widget
                 withJavaUtilList:(id<JavaUtilList>)rows
               withRAREActionLink:(RAREActionLink *)link;
@end

@interface ComSparsewareBellavistaVitals_ChartHandler : ComSparsewareBellavistaaChartHandler {
}

- (id)initWithComSparsewareBellavistaVitals:(ComSparsewareBellavistaVitals *)outer$
                       withRAREUTJSONObject:(RAREUTJSONObject *)chartsInfo;
- (void)configureChartWithRAREiWidget:(id<RAREiWidget>)context
                    withRARESPOTChart:(RARESPOTChart *)cfg
                         withNSString:(NSString *)key
                withRAREChartDataItem:(RAREChartDataItem *)series;
@end

#endif // _ComSparsewareBellavistaVitals_H_
